public class BundlePackDefDefines
{
	public const string STARTERPACK = "2370";

	public const string INGREDIENTPACK_FOREST = "11985";

	public const string INGREDIENTPACK_SWAMP = "11986";

	public const string INGREDIENTPACK_BLOODTUNDRA = "11987";

	public const string ASTRALSHOPBUNDLE_DRAGON = "14867";

	public const string ASTRALSHOPBUNDLE_SEASONPASS_01 = "14946";

	public const string TESTTIERREWARD_TESTTIERREWARDBUNDLE = "15024";

	public const string IAPSHOP_STARFRAGMENTS_BUNDLEA = "15228";

	public const string IAPSHOP_STARFRAGMENTS_BUNDLEB = "15230";

	public const string TIERREWARD_DYESSET_SET1 = "15861";

	public const string TIERREWARD_CREATURE_JACKALOPE = "15862";

	public const string TIERREWARD_CLOTHINGSET_JESTERSET = "16652";

	public const string TIERREWARD_INGREDIENTPACK_COMMON_BLOODTUNDRA = "16658";

	public const string TIERREWARD_INGREDIENTPACK_COMMON_FOREST = "16659";

	public const string TIERREWARD_INGREDIENTPACK_COMMON_SWAMP = "16660";

	public const string TIERREWARD_FURNITURESET_SUNKENTHICKET = "16678";

	public const string TIERREWARD_CLOTHINGSET_ANGULARSET = "16684";

	public const string TIERREWARD_JACKALOPE_MODPACK = "16685";

	public const string TIERREWARD_INGREDIENTPACK_UNCOMMON_BLOODTUNDRA = "16691";

	public const string TIERREWARD_INGREDIENTPACK_UNCOMMON_FOREST = "16692";

	public const string TIERREWARD_INGREDIENTPACK_UNCOMMON_SWAMP = "16693";

	public const string TIERREWARD_INGREDIENTPACK_RARE_SWAMP = "16704";

	public const string TIERREWARD_INGREDIENTPACK_RARE_FOREST = "16705";

	public const string TIERREWARD_INGREDIENTPACK_RARE_BLOODTUNDRA = "16706";

	public const string TIERREWARD_FURNITURESET_CHATEAUSET = "16719";

	public const string TIERREWARD_CLOTHINGSET_ARTISTSET = "16738";

	public const string TIERREWARD_JACKALOPE_HEAD = "16765";

	public const string TIERREWARD_JACKALOPE_LEG = "16766";

	public const string TIERREWARD_JACKALOPE_TAIL = "16767";

	public const string TIERREWARD_LOCKPICKS_3 = "16768";

	public const string TIERREWARD_LOCKPICKS_15 = "16769";

	public const string TIERREWARD_JACKALOPE_LOOK = "16770";

	public const string TIERREWARD_TRADERPORT_LOOK = "16771";

	public const string ASTRALSHOPBUNDLE_SANCTUARY_CITYFERA = "16938";

	public const string ASTRALSHOPBUNDLE_SANCTUARY_CASTLE = "16939";

	public const string IAPSHOP_STARFRAGMENTS_BUNDLEC = "16971";

	public const string IAPSHOP_STARFRAGMENTS_BUNDLED = "16972";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_HEAD002 = "17778";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_EARS002 = "18653";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_HORNS002 = "18654";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_LEGS002 = "18655";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_TAIL002 = "18656";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_EARS003 = "18657";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_HEAD003 = "18658";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_HORNS003 = "18659";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_LEGS003 = "18660";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_TAIL003 = "18661";

	public const string ASTRALSHOPBUNDLE_SANCTUARY_CHATEAU = "18662";

	public const string TIERREWARD_CREATURE_WEREWOLF = "20214";

	public const string TIERREWARD_WEREWOLF_SMALL_HEAD = "20216";

	public const string TIERREWARD_WEREWOLF_SMALL_EAR = "20217";

	public const string TIERREWARD_WEREWOLF_SMALL_HORNS = "20218";

	public const string TIERREWARD_WEREWOLF_SMALL_LEGS = "20219";

	public const string TIERREWARD_WEREWOLF_SMALL_TAIL = "20220";

	public const string TIERREWARD_CLOTHINGSET_WICKEDSET = "20221";

	public const string TIERREWARD_CLOTHINGSET_GROOVYSET = "20226";

	public const string TIERREWARD_CLOTHINGSET_TATTEREDSET = "20227";

	public const string TIERREWARD_FURNITURESET_BALLROOMSET = "20228";

	public const string TIERREWARD_FURNITURESET_VOYAGERSET = "20229";

	public const string TIERREWARD_WEREWOLF_EPIC_EAR = "20236";

	public const string TIERREWARD_WEREWOLF_EPIC_HEAD = "20237";

	public const string TIERREWARD_WEREWOLF_EPIC_HORNS = "20238";

	public const string TIERREWARD_WEREWOLF_EPIC_LEGS = "20239";

	public const string TIERREWARD_WEREWOLF_EPIC_TAIL = "20240";

	public const string TIERREWARD_WEREWOLF_ONEOFF_EAR = "20241";

	public const string TIERREWARD_WEREWOLF_ONEOFF_HEAD = "20242";

	public const string TIERREWARD_WEREWOLF_ONEOFF_HORNS = "20243";

	public const string TIERREWARD_WEREWOLF_ONEOFF_LEGS = "20244";

	public const string TIERREWARD_WEREWOLF_ONEOFF_TAIL = "20245";

	public const string TIERREWARD_WEREWOLF_LOOK = "20262";

	public const string TIERREWARD_SUNKENTHICKET_LOOK = "20271";

	public const string ASTRALSHOPBUNDLE_SEASONPASS_02 = "20429";

	public const string ASTRALSHOPBUNDLE_SANCTUARY_HAUNTED = "21966";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_EARS004 = "21973";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_EARS005 = "21974";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_HEAD004 = "21975";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_HEAD005 = "21976";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_HORNS004 = "21977";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_HORNS005 = "21978";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_LEGS004 = "21979";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_LEGS005 = "21980";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_TAIL004 = "21981";

	public const string ASTRALSHOPBUNDLE_DRAGONMOD_TAIL005 = "21982";

	public const string XPREWARD_INGREDIENTPACK_LEVEL2 = "22057";

	public const string XPREWARD_KITSUNEMOD_LEVEL5 = "22058";

	public const string XPREWARD_INGREDIENTPACK_LEVEL4 = "22059";

	public const string XPREWARD_INGREDIENTPACK_LEVEL7 = "22060";

	public const string XPREWARD_KITSUNEMOD_LEVEL10 = "22061";

	public const string XPREWARD_INGREDIENTPACK_LEVEL12 = "22069";

	public const string XPREWARD_INGREDIENTPACK_LEVEL13 = "22070";

	public const string XPREWARD_KITSUNEMOD_LEVEL15 = "22077";

	public const string XPREWARD_KITSUNEMOD_LEVEL20 = "22078";

	public const string XPREWARD_CLOTHINGPACK_LEVEL22 = "22079";

	public const string XPREWARD_INGREDIENTPACK_LEVEL23 = "22080";

	public const string XPREWARD_KITSUNEMOD_LEVEL99 = "22081";

	public const string XPREWARD_JUNKPACK_LEVEL26 = "22082";

	public const string XPREWARD_SENRIMOD_LEVEL25 = "22083";

	public const string XPREWARD_INGREDIENTPACK_LEVEL31 = "22084";

	public const string XPREWARD_INGREDIENTPACK_LEVEL33 = "22085";

	public const string XPREWARD_SENRIMOD_LEVEL30 = "22086";

	public const string XPREWARD_BASEINGREDIENTSPACK_LEVEL36 = "22087";

	public const string XPREWARD_INGREDIENTPACK_LEVEL37 = "22088";

	public const string XPREWARD_DYESPACK_LEVEL39 = "22089";

	public const string XPREWARD_SENRIMOD_LEVEL35 = "22090";

	public const string XPREWARD_INGREDIENTPACK_LEVEL42 = "22091";

	public const string XPREWARD_SENRIMOD_LEVEL40 = "22092";

	public const string XPREWARD_BASEINGREDIENTSPACK_LEVEL46 = "22093";

	public const string XPREWARD_SWAMPINGREDIENTSPACK_LEVEL49 = "22094";

	public const string XPREWARD_SENRIMOD_LEVEL45 = "22095";

	public const string XPREWARD_JUNKPACK_LEVEL51 = "22096";

	public const string XPREWARD_INGREDIENTPACK_LEVEL52 = "22097";

	public const string XPREWARD_INGREDIENTPACK_LEVEL53 = "22098";

	public const string XPREWARD_KITSUNEMOD_LEVEL55 = "22099";

	public const string XPREWARD_BASEINGREDIENTSPACK_LEVEL58 = "22100";

	public const string XPREWARD_KITSUNEMOD_LEVEL60 = "22101";

	public const string XPREWARD_DYESPACK_LEVEL61 = "22102";

	public const string XPREWARD_JUNKPACKPACK_LEVEL62 = "22103";

	public const string XPREWARD_FURNITURESET_LEVEL63 = "22104";

	public const string XPREWARD_FORESTINGREDIENTSPACK_LEVEL66 = "22105";

	public const string XPREWARD_KITSUNEMOD_LEVEL65 = "22106";

	public const string XPREWARD_KITSUNEMOD_LEVEL70 = "22107";

	public const string XPREWARD_DYESPACK_LEVEL71 = "22108";

	public const string XPREWARD_JUNKPACK_LEVEL74 = "22109";

	public const string XPREWARD_KITSUNEMOD_LEVEL50 = "22110";

	public const string XPREWARD_JUNKPACK_LEVEL76 = "22111";

	public const string XPREWARD_BASEINGREDIENTSPACK_LEVEL79 = "22112";

	public const string XPREWARD_SENRIMOD_LEVEL80 = "22113";

	public const string XPREWARD_CLOTHINGPACK_LEVEL83 = "22114";

	public const string XPREWARD_SENRIMOD_LEVEL85 = "22115";

	public const string XPREWARD_DYESPACK_LEVEL86 = "22117";

	public const string XPREWARD_FURNITURESET_LEVEL87 = "22118";

	public const string XPREWARD_JUNKPACK_LEVEL89 = "22119";

	public const string XPREWARD_SENRIMOD_LEVEL90 = "22120";

	public const string XPREWARD_FURNITURESET_LEVEL91 = "22121";

	public const string XPREWARD_JUNKPACK_LEVEL92 = "22122";

	public const string XPREWARD_CLOTHINGPACK_LEVEL93 = "22123";

	public const string XPREWARD_BLOODTUNDRAINGREDIENTSPACK_LEVEL94 = "22124";

	public const string XPREWARD_SENRIMOD_LEVEL95 = "22125";

	public const string XPREWARD_JUNKPACK_LEVEL96 = "22126";

	public const string XPREWARD_DYESPACK_LEVEL98 = "22127";

	public const string XPREWARD_SENRIMOD_LEVEL75 = "22128";

	public const string XPREWARD_UNLOCKWINGS_SMALLWINGS = "22423";

	public const string XPREWARD_UNLOCKWINGS_MEDIUMWINGS = "22439";

	public const string XPREWARD_UNLOCKWINGS_EPICWINGS = "22440";

	public const string ASTRALSHOPBUNDLE_SEASONPASS_03 = "23371";

	public const string TIERREWARD_CLOTHINGSET_CLOUDBURSTSET = "23459";

	public const string TIERREWARD_CLOTHINGSET_KNIGHTSET = "23460";

	public const string TIERREWARD_CLOTHINGSET_RAVISHINGSET = "23461";

	public const string TIERREWARD_FURNITURESET_ICYSET = "23462";

	public const string TIERREWARD_FURNITURESET_COZYSET = "23463";

	public const string TIERREWARD_CREATURE_KIRIN = "23464";

	public const string TIERREWARD_KIRIN_HEAD_SMALL = "23465";

	public const string TIERREWARD_KIRIN_LEG_SMALL = "23466";

	public const string TIERREWARD_KIRIN_EAR_SMALL = "23467";

	public const string TIERREWARD_KIRIN_HORN_SMALL = "23468";

	public const string TIERREWARD_KIRIN_TAIL_SMALL = "23469";

	public const string TIERREWARD_KIRIN_EAR_EPIC = "23470";

	public const string TIERREWARD_KIRIN_EAR_ONEOFF = "23471";

	public const string TIERREWARD_KIRIN_HEAD_EPIC = "23472";

	public const string TIERREWARD_KIRIN_HEAD_ONEOFF = "23473";

	public const string TIERREWARD_KIRIN_HORN_EPIC = "23474";

	public const string TIERREWARD_KIRIN_HORN_ONEOFF = "23475";

	public const string TIERREWARD_KIRIN_LEG_EPIC = "23476";

	public const string TIERREWARD_KIRIN_LEG_ONEOFF = "23477";

	public const string TIERREWARD_KIRIN_TAIL_EPIC = "23478";

	public const string TIERREWARD_KIRIN_TAIL_ONEOFF = "23479";

	public const string TIERREWARD_KIRIN_LOOK = "23483";

	public const string TIERREWARD_VOYAGER_LOOK = "23484";

	public const string ASTRALSHOPBUNDLE_SANCTUARY_WINTERCITADEL = "23860";

	public const string REUSE = "24123";

	public const string TIERREWARD_CLOTHINGSET_WINTERWINGSET = "25058";

	public const string TIERREWARD_CLOTHINGSET_SNOWPETALSET = "25059";

	public const string TIERREWARD_CLOTHINGSET_BEWITCHINGSET = "25060";

	public const string TIERREWARD_FURNITURESET_FROSTWORNSET = "25061";

	public const string TIERREWARD_FURNITURESET_GLOWROOTSET = "25062";

	public const string TIERREWARD_CREATURE_SHINIGAMI = "25063";

	public const string TIERREWARD_SHINIGAMI_LOOK = "25064";

	public const string TIERREWARD_SHINIGAMI_HEAD_SMALL = "25065";

	public const string TIERREWARD_SHINIGAMI_EARS_SMALL = "25068";

	public const string TIERREWARD_SHINIGAMI_HORNS_SMALL = "25071";

	public const string TIERREWARD_SHINIGAMI_LEGS_SMALL = "25074";

	public const string TIERREWARD_SHINIGAMI_TAIL_SMALL = "25077";

	public const string TIERREWARD_FROSTFETE_LOOK = "25080";

	public const string ASTRALSHOPBUNDLE_SEASONPASS_04 = "25239";

	public const string STARTERPACK_POST_TUTORIAL = "25458";

	public const string ASTRALSHOPBUNDLE_JACKALOPE = "25793";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_EARS004 = "25794";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_EARS005 = "25795";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_HEAD004 = "25796";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_HEAD005 = "25797";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_HORNS004 = "25798";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_HORNS005 = "25799";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_LEGS004 = "25800";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_LEGS005 = "25801";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_TAIL004 = "25802";

	public const string ASTRALSHOPBUNDLE_WEREWOLFMOD_TAIL005 = "25803";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_EARS002 = "26505";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_EARS003 = "26506";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_HEAD002 = "26507";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_HEAD003 = "26508";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_HORNS003 = "26509";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_HORNS002 = "26510";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_LEGS002 = "26511";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_LEGS003 = "26512";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_TAIL002 = "26513";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_TAIL003 = "26514";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_EARS001 = "26912";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_HEAD001 = "26913";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_HORNS001 = "26914";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_LEGS001 = "26915";

	public const string ASTRALSHOPBUNDLE_JACKALOPEMOD_TAIL001 = "26916";

	public const string TIERREWARD_CREATURE_PHOENIX = "27193";

	public const string TIERREWARD_PHOENIX_LOOK = "27195";

	public const string TIERREWARD_PHOENIX_EPIC_EAR = "27214";

	public const string TIERREWARD_PHOENIX_EPIC_HEAD = "27215";

	public const string TIERREWARD_PHOENIX_EPIC_HORNS = "27216";

	public const string TIERREWARD_PHOENIX_EPIC_LEGS = "27217";

	public const string TIERREWARD_PHOENIX_EPIC_TAIL = "27218";

	public const string TIERREWARD_PHOENIX_ONEOFF_EAR = "27219";

	public const string TIERREWARD_PHOENIX_ONEOFF_HEAD = "27220";

	public const string TIERREWARD_PHOENIX_ONEOFF_HORNS = "27221";

	public const string TIERREWARD_PHOENIX_ONEOFF_LEGS = "27222";

	public const string TIERREWARD_PHOENIX_ONEOFF_TAIL = "27223";

	public const string TIERREWARD_PHOENIX_SMALL_EAR = "27224";

	public const string TIERREWARD_PHOENIX_SMALL_HEAD = "27225";

	public const string TIERREWARD_PHOENIX_SMALL_HORNS = "27226";

	public const string TIERREWARD_PHOENIX_SMALL_LEGS = "27227";

	public const string TIERREWARD_PHOENIX_SMALL_TAIL = "27228";

	public const string TIERREWARD_CLOTHINGSET_BALLOONISTSET = "27229";

	public const string TIERREWARD_CLOTHINGSET_PEACHBURSTSET = "27230";

	public const string TIERREWARD_CLOTHINGSET_RISINGSET = "27231";

	public const string TIERREWARD_FURNITURESET_SPRINGCLOVERSET = "27232";

	public const string TIERREWARD_FURNITURESET_WHIMSICALSET = "27233";

	public const string TIERREWARD_ROSECOTTAGE_LOOK = "27241";

	public const string ASTRALSHOPBUNDLE_SEASONPASS_05 = "27284";

	public const string ASTRALSHOPBUNDLE_WEREWOLF = "27780";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_EARS002 = "27781";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_EARS003 = "27782";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_HEAD002 = "27783";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_HEAD003 = "27784";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_HORNS002 = "27785";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_HORNS003 = "27786";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_LEGS002 = "27787";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_LEGS003 = "27788";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_TAIL002 = "27789";

	public const string ASTRALSHOPBUNDLE_SHINIGAMIMOD_TAIL003 = "27790";

	public const string ASTRALSHOPBUNDLE_SEASONPASS_06 = "29318";

	public const string TIERREWARD_CLOTHINGSET_PARTYGLOWSET = "29624";

	public const string TIERREWARD_CLOTHINGSET_CAFESET = "29625";

	public const string TIERREWARD_CLOTHINGSET_SPASET = "29626";

	public const string TIERREWARD_FURNITURESET_CAFESET = "29627";

	public const string TIERREWARD_FURNITURESET_SPASET = "29628";

	public const string TIERREWARD_FAE_HEAD_SMALL = "29629";

	public const string TIERREWARD_FAE_LEG_SMALL = "29630";

	public const string TIERREWARD_FAE_EAR_SMALL = "29631";

	public const string TIERREWARD_FAE_HORN_SMALL = "29632";

	public const string TIERREWARD_FAE_TAIL_SMALL = "29633";

	public const string TIERREWARD_FAE_LOOK = "29634";

	public const string TIERREWARD_CREATURE_FAE = "29635";

	public const string TIERREWARD_WOODLANDCOTTAGE_LOOK = "29636";

	public const string ASTRALSHOPBUNDLE_PHOENIX = "30184";

	public const string LOOK_EXTRASLOT = "30198";
}
