public class LootDefDefines
{
	public const string TEST = "1920";

	public const string TEST2 = "1921";

	public const string TEST3 = "1922";

	public const string TEST_ENIGMA = "3672";

	public const string TEST_ENIGMA1 = "3866";

	public const string CASUALGAME_RUNES_MIASMA03 = "3937";

	public const string CASUALGAME_RUNES_FLAME01 = "3938";

	public const string CASUALGAME_RUNES_FLAME03 = "3939";

	public const string CASUALGAME_RUNES_FLAME02 = "3940";

	public const string CASUALGAME_RUNES_FLORA01 = "3941";

	public const string CASUALGAME_RUNES_FLORA02 = "3942";

	public const string CASUALGAME_RUNES_FLORA03 = "3943";

	public const string CASUALGAME_RUNES_MIASMA01 = "3944";

	public const string CASUALGAME_RUNES_MIASMA02 = "3945";

	public const string CASUALGAME_COMMON_LIKES10 = "3947";

	public const string CASUALGAME_COMMON_LIKES25 = "3948";

	public const string CASUALGAME_COMMON_LIKES50 = "3949";

	public const string CASUALGAME_RUNES_REWARDS_FORESTRARE = "3950";

	public const string CASUALGAME_RUNES_REWARDS_SWAMPRARE = "3951";

	public const string NEW = "4496";

	public const string CASUALGAME_RUNES_FLAME04 = "4595";

	public const string CASUALGAME_RUNES_FLAME05 = "4599";

	public const string CASUALGAME_RUNES_FLAME06 = "4600";

	public const string CASUALGAME_RUNES_FLAME07 = "4601";

	public const string CASUALGAME_RUNES_FLAME09 = "4602";

	public const string CASUALGAME_RUNES_FLAME10 = "4603";

	public const string CASUALGAME_RUNES_FLAME11 = "4604";

	public const string CASUALGAME_RUNES_FLAME12 = "4605";

	public const string CASUALGAME_RUNES_FLAME13 = "4606";

	public const string CASUALGAME_RUNES_FLAME14 = "4607";

	public const string CASUALGAME_RUNES_FLAME16 = "4608";

	public const string CASUALGAME_RUNES_FLAME17 = "4609";

	public const string CASUALGAME_RUNES_FLAME18 = "4610";

	public const string CASUALGAME_RUNES_FLAME19 = "4611";

	public const string CASUALGAME_RUNES_FLAME20 = "4612";

	public const string CASUALGAME_RUNES_FLORA04 = "4615";

	public const string CASUALGAME_RUNES_FLORA05 = "4616";

	public const string CASUALGAME_RUNES_FLORA06 = "4617";

	public const string CASUALGAME_RUNES_FLORA07 = "4618";

	public const string CASUALGAME_RUNES_FLORA08 = "4619";

	public const string CASUALGAME_RUNES_FLORA09 = "4620";

	public const string CASUALGAME_RUNES_FLORA10 = "4621";

	public const string CASUALGAME_RUNES_FLORA11 = "4622";

	public const string CASUALGAME_RUNES_FLORA12 = "4623";

	public const string CASUALGAME_RUNES_FLORA13 = "4624";

	public const string CASUALGAME_RUNES_FLORA14 = "4625";

	public const string CASUALGAME_RUNES_FLORA15 = "4626";

	public const string CASUALGAME_RUNES_FLORA16 = "4627";

	public const string CASUALGAME_RUNES_FLORA17 = "4628";

	public const string CASUALGAME_RUNES_FLORA18 = "4629";

	public const string CASUALGAME_RUNES_FLORA19 = "4630";

	public const string CASUALGAME_RUNES_FLORA20 = "4631";

	public const string CASUALGAME_RUNES_MIASMA04 = "4632";

	public const string CASUALGAME_RUNES_MIASMA05 = "4633";

	public const string CASUALGAME_RUNES_MIASMA06 = "4634";

	public const string CASUALGAME_RUNES_MIASMA07 = "4635";

	public const string CASUALGAME_RUNES_MIASMA08 = "4636";

	public const string CASUALGAME_RUNES_MIASMA09 = "4637";

	public const string CASUALGAME_RUNES_MIASMA10 = "4638";

	public const string CASUALGAME_RUNES_MIASMA11 = "4639";

	public const string CASUALGAME_RUNES_MIASMA12 = "4640";

	public const string CASUALGAME_RUNES_MIASMA13 = "4641";

	public const string CASUALGAME_RUNES_MIASMA14 = "4642";

	public const string CASUALGAME_RUNES_MIASMA15 = "4643";

	public const string CASUALGAME_RUNES_MIASMA16 = "4644";

	public const string CASUALGAME_RUNES_MIASMA17 = "4645";

	public const string CASUALGAME_RUNES_MIASMA18 = "4646";

	public const string CASUALGAME_RUNES_MIASMA19 = "4647";

	public const string CASUALGAME_RUNES_MIASMA20 = "4648";

	public const string CASUALGAME_RUNES_FLAME08 = "4651";

	public const string CASUALGAME_RUNES_FLAME15 = "4652";

	public const string CASUALGAME_TWIGGLEBUILDERS_2STAR_L25_30_35_40_45 = "4935";

	public const string CASUALGAME_TWIGGLEBUILDERS_2STAR_L50 = "4936";

	public const string CASUALGAME_TWIGGLEBUILDERS_1STAR_L50 = "4939";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STAR_L1_4 = "5079";

	public const string CASUALGAME_TWIGGLEBUILDERS_2STAR_L6_24 = "5080";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STAR_L6_24 = "5081";

	public const string CASUALGAME_TWIGGLEBUILDERS_REWARDS_CLOTHING = "5082";

	public const string CASUALGAME_DOORDYE_REWARDS_FURNITURE = "5083";

	public const string CASUALGAME_DOORDYE_REWARDS_DYE = "5084";

	public const string CASUALGAME_DOORDYE_REWARDS_RAREINGREDIENTS = "5085";

	public const string CASUALGAME_DOORDYE_3STAR_L10_20_30_40 = "5086";

	public const string CASUALGAME_DOORDYE_3STARREPLAY_L10_20_30_40 = "5087";

	public const string TEST_ENIGMA_COPY = "5091";

	public const string TEST_ENIGMA1_COPY = "5092";

	public const string CASUALGAME_COMMON_LIKES75 = "5287";

	public const string REWARD_CURRENCY_LIKES25 = "5496";

	public const string REWARD_CURRENCY_LIKES50 = "5497";

	public const string REWARD_CURRENCY_LIKES75 = "5501";

	public const string REWARD_CURRENCY_LIKES100 = "5502";

	public const string REWARD_CURRENCY_LIKES125 = "5503";

	public const string REWARD_CURRENCY_LIKES150 = "5504";

	public const string REWARD_CURRENCY_LIKES175 = "5505";

	public const string REWARD_CURRENCY_LIKES200 = "5506";

	public const string REWARD_CURRENCY_LIKES300 = "5507";

	public const string REWARD_CURRENCY_LIKES400 = "5508";

	public const string REWARD_CURRENCY_LIKES500 = "5509";

	public const string REWARD_CURRENCY_LIKES750 = "5510";

	public const string REWARD_CURRENCY_LIKES1000 = "5511";

	public const string ENIGMA_SHARDTIARA = "5594";

	public const string TEST3_COPY = "5613";

	public const string HIKINGDISASTER_EXPERTCHEST_1 = "5614";

	public const string REWARD_FURNITURE_NETCHWEEDNEEDLECHAIR = "5622";

	public const string REWARD_CURRENCY_LIKES750_COPY = "5623";

	public const string HIKINGDISASTER_BC3 = "5643";

	public const string HIKINGDISASTER_BC4 = "5644";

	public const string HIKINGDISASTER_BC5 = "5645";

	public const string HIKINGDISASTER_BC6 = "5646";

	public const string HIKINGDISASTER_BC7 = "5647";

	public const string HIKINGDISASTER_BC8 = "5648";

	public const string HIKINGDISASTER_BC9 = "5649";

	public const string HIKINGDISASTER_BC10 = "5650";

	public const string HIKINGDISASTER_BC11 = "5651";

	public const string HIKINGDISASTER_BC12 = "5652";

	public const string HIKINGDISASTER_BC13 = "5653";

	public const string HIKINGDISASTER_BC14 = "5654";

	public const string HIKINGDISASTER_BC15 = "5655";

	public const string HIKINGDISASTER_BC16 = "5656";

	public const string HIKINGDISASTER_BC17 = "5657";

	public const string HIKINGDISASTER_BC18 = "5658";

	public const string HIKINGDISASTER_BC19 = "5659";

	public const string HIKINGDISASTER_BC20 = "5660";

	public const string HIKINGDISASTER_SC1 = "5661";

	public const string HIKINGDISASTER_SC2 = "5662";

	public const string HIKINGDISASTER_SC3 = "5663";

	public const string HIKINGDISASTER_SC4 = "5664";

	public const string HIKINGDISASTER_SC5 = "5665";

	public const string HIKINGDISASTER_SC6 = "5666";

	public const string HIKINGDISASTER_SC7 = "5667";

	public const string HIKINGDISASTER_SC8 = "5668";

	public const string HIKINGDISASTER_GC1 = "5669";

	public const string HIKINGDISASTER_GC2 = "5670";

	public const string HIKINGDISASTER_GC3 = "5671";

	public const string HIKINGDISASTER_GC4 = "5672";

	public const string HIKINGDISASTER_GC5 = "5673";

	public const string HIKINGDISASTER_GC6 = "5674";

	public const string HIKINGDISASTER_GC7 = "5675";

	public const string CASUALGAME_TWIGGLEBUILDERS_1STAR_L1_4 = "6566";

	public const string CASUALGAME_TWIGGLEBUILDERS_2STAR_L1_4 = "6567";

	public const string CASUALGAME_TWIGGLEBUILDERS_2STAR_L5_10_15_20 = "6568";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STAR_L5_10_15_20 = "6569";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STARREPLAY_L5_10_15_20 = "6570";

	public const string CASUALGAME_TWIGGLEBUILDERS_1STAR_L6_24 = "6571";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STARREPLAY_L1_4 = "6572";

	public const string CASUALGAME_TWIGGLEBUILDERS_1STAR_L5_10_15_20 = "6573";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STARREPLAY_L6_24 = "6574";

	public const string CASUALGAME_TWIGGLEBUILDERS_1STAR_L25_30_35_40_45 = "6575";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STAR_L25_30_35_40_45 = "6576";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STARREPLAY_L25_30_35_40_45 = "6577";

	public const string CASUALGAME_TWIGGLEBUILDERS_1STAR_L26_49 = "6578";

	public const string CASUALGAME_TWIGGLEBUILDERS_2STAR_L26_49 = "6579";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STAR_L26_49 = "6580";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STARREPLAY_L26_49 = "6581";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STAR_L50 = "6582";

	public const string CASUALGAME_TWIGGLEBUILDERS_3STARREPLAY_L50 = "6583";

	public const string CASUALGAME_TWIGGLEBUILDERS_REWARDS_FURNITURE = "6584";

	public const string CASUALGAME_TWIGGLEBUILDERS_REWARDS_DYE = "6585";

	public const string CASUALGAME_DOORDYE_REWARDS_CLOTHING = "6586";

	public const string CASUALGAME_TWIGGLEBUILDERS_REWARDS_RAREINGREDIENTS = "6587";

	public const string CASUALGAME_TWIGGLEBUILDERS_REWARDS_COMMONINGREDIENTS = "6588";

	public const string CASUALGAME_TWIGGLEBUILDERS_REWARDS_UNCOMMONINGREDIENTS = "6589";

	public const string CASUALGAME_DOORDYE_REWARDS_COMMONINGREDIENTS = "6590";

	public const string CASUALGAME_DOORDYE_REWARDS_UNCOMMONINGREDIENTS = "6591";

	public const string CASUALGAME_DOORDYE_1STAR_L1_9 = "6592";

	public const string CASUALGAME_DOORDYE_2STAR_L1_9 = "6593";

	public const string CASUALGAME_DOORDYE_3STAR_L1_9 = "6594";

	public const string CASUALGAME_DOORDYE_3STARREPLAY_L1_9 = "6595";

	public const string CASUALGAME_DOORDYE_1STAR_L10_20_30_40 = "6596";

	public const string CASUALGAME_DOORDYE_2STAR_L10_20_30_40 = "6597";

	public const string CASUALGAME_COMMON_LIKES15 = "7070";

	public const string CASUALGAME_COMMON_LIKES100 = "7071";

	public const string CASUALGAME_COMMON_LIKES125 = "7072";

	public const string CASUALGAME_COMMON_LIKES150 = "7073";

	public const string CASUALGAME_RUNES_REWARDS_LIKES_T1_5 = "7074";

	public const string CASUALGAME_RUNES_REWARDS_LIKES_T6_10 = "7075";

	public const string CASUALGAME_RUNES_REWARDS_LIKES_T11_15 = "7076";

	public const string CASUALGAME_RUNES_REWARDS_LIKES_T16_20 = "7077";

	public const string CASUALGAME_RUNES_REWARDS_LIKES_T20 = "7078";

	public const string CASUALGAME_RUNES_REWARDS_DYE = "7079";

	public const string CASUALGAME_RUNES_REWARDS_CLOTHING = "7080";

	public const string CASUALGAME_RUNES_REWARDS_FURNITURE = "7081";

	public const string CASUALGAME_RUNES_REWARDS_SWAMPCOMMONA = "7082";

	public const string CASUALGAME_RUNES_REWARDS_SWAMPCOMMONB = "7083";

	public const string CASUALGAME_RUNES_REWARDS_SWAMPCOMMONC = "7084";

	public const string CASUALGAME_RUNES_REWARDS_FORESTCOMMONA = "7085";

	public const string CASUALGAME_RUNES_REWARDS_FORESTCOMMONB = "7086";

	public const string CASUALGAME_RUNES_REWARDS_FORESTCOMMONC = "7087";

	public const string CASUALGAME_RUNES_REWARDS_SWAMPUNCOMMONA = "7088";

	public const string CASUALGAME_RUNES_REWARDS_SWAMPUNCOMMONB = "7089";

	public const string CASUALGAME_RUNES_REWARDS_SWAMPUNCOMMONC = "7090";

	public const string CASUALGAME_RUNES_REWARDS_FORESTUNCOMMONA = "7091";

	public const string CASUALGAME_RUNES_REWARDS_FORESTUNCOMMONB = "7092";

	public const string CASUALGAME_RUNES_REWARDS_FORESTUNCOMMONC = "7093";

	public const string CASUALGAME_COMMON_LIKES200 = "7126";

	public const string CASUALGAME_DOORDYE_1STAR_L11_49 = "7145";

	public const string CASUALGAME_DOORDYE_2STAR_L11_49 = "7146";

	public const string CASUALGAME_DOORDYE_3STAR_L11_49 = "7147";

	public const string CASUALGAME_DOORDYE_3STARREPLAY_L11_49 = "7148";

	public const string CASUALGAME_DOORDYE_1STAR_L50_60_70_80_90 = "7149";

	public const string CASUALGAME_DOORDYE_2STAR_L50_60_70_80_90 = "7150";

	public const string CASUALGAME_DOORDYE_3STAR_L50_60_70_80_90 = "7151";

	public const string CASUALGAME_DOORDYE_3STARREPLAY_L50_60_70_80_90 = "7152";

	public const string CASUALGAME_DOORDYE_1STAR_L51_99 = "7153";

	public const string CASUALGAME_DOORDYE_2STAR_L51_99 = "7154";

	public const string CASUALGAME_DOORDYE_3STAR_L51_99 = "7155";

	public const string CASUALGAME_DOORDYE_3STARREPLAY_L51_99 = "7156";

	public const string CASUALGAME_DOORDYE_1STAR_L100 = "7157";

	public const string CASUALGAME_DOORDYE_2STAR_L100 = "7158";

	public const string CASUALGAME_DOORDYE_3STAR_L100 = "7159";

	public const string CASUALGAME_DOORDYE_3STARREPLAY_L100 = "7160";

	public const string TREASURECHEST_BASIC = "7162";

	public const string TREASURECHEST_BRONZE_NUCRYSTALLIFE_BC_1 = "7163";

	public const string TREASURECHEST_BRONZE_NUCRYSTALLIFE_BC_2 = "7164";

	public const string TREASURECHEST_BRONZE_NUCRYSTALLIFE_BC_3 = "7165";

	public const string TREASURECHEST_BRONZE_NUCRYSTALLIFE_BC_4 = "7166";

	public const string TREASURECHEST_BRONZE_NUCRYSTALLIFE_BC_5 = "7167";

	public const string TREASURECHEST_SILVER_NUCRYSTALLIFE_SC_1 = "7168";

	public const string TREASURECHEST_SILVER_NUCRYSTALLIFE_SC_2 = "7169";

	public const string TREASURECHEST_SILVER_NUCRYSTALLIFE_SC_3 = "7170";

	public const string TREASURECHEST_GOLD_NUCRYSTALLIFE_GC_1 = "7171";

	public const string TREASURECHEST_GOLD_NUCRYSTALLIFE_GC_2 = "7172";

	public const string TREASURECHEST_GOLD_BACKSCRATCHERS_GC_1 = "7173";

	public const string TREASURECHEST_GOLD_DETECTIVEKOBOLD_GC_1 = "7174";

	public const string TREASURECHEST_GOLD_SUCKEREDIN_GC_1 = "7175";

	public const string TREASURECHEST_GOLD_PERFECTPARTY_GC_1 = "7176";

	public const string TREASURECHEST_GOLD_PROVEFISHINGSKILLS_GC_1 = "7177";

	public const string TREASURECHEST_GOLD_STATUEOFLIMITATIONS_GC_1 = "7178";

	public const string TREASURECHEST_GOLD_BACKSCRATCHERS_GC_2 = "7179";

	public const string TREASURECHEST_GOLD_DETECTIVEKOBOLD_GC_2 = "7180";

	public const string TREASURECHEST_GOLD_SUCKEREDIN_GC_2 = "7181";

	public const string TREASURECHEST_GOLD_PERFECTPARTY_GC_2 = "7182";

	public const string TREASURECHEST_GOLD_PROVEFISHINGSKILLS_GC_2 = "7183";

	public const string TREASURECHEST_GOLD_STATUEOFLIMITATIONS_GC_2 = "7184";

	public const string TREASURECHEST_SILVER_DETECTIVEKOBOLD_SC_1 = "7185";

	public const string TREASURECHEST_SILVER_BACKSCRATCHERS_SC_1 = "7186";

	public const string TREASURECHEST_SILVER_SUCKEREDIN_SC_1 = "7187";

	public const string TREASURECHEST_SILVER_PERFECTPARTY_SC_1 = "7188";

	public const string TREASURECHEST_SILVER_PROVEFISHINGSKILLS_SC_1 = "7189";

	public const string TREASURECHEST_SILVER_STATUEOFLIMITATIONS_SC_1 = "7191";

	public const string TREASURECHEST_SILVER_BACKSCRATCHERS_SC_2 = "7192";

	public const string TREASURECHEST_SILVER_DETECTIVEKOBOLD_SC_2 = "7193";

	public const string TREASURECHEST_SILVER_SUCKEREDIN_SC_2 = "7195";

	public const string TREASURECHEST_SILVER_PERFECTPARTY_SC_2 = "7197";

	public const string TREASURECHEST_SILVER_PROVEFISHINGSKILLS_SC_2 = "7198";

	public const string TREASURECHEST_SILVER_STATUEOFLIMITATIONS_SC_2 = "7199";

	public const string TREASURECHEST_SILVER_BACKSCRATCHERS_SC_3 = "7200";

	public const string TREASURECHEST_SILVER_DETECTIVEKOBOLD_SC_3 = "7201";

	public const string TREASURECHEST_SILVER_SUCKEREDIN_SC_3 = "7202";

	public const string TREASURECHEST_SILVER_PERFECTPARTY_SC_3 = "7203";

	public const string TREASURECHEST_SILVER_PROVEFISHINGSKILLS_SC_3 = "7204";

	public const string TREASURECHEST_SILVER_STATUEOFLIMITATIONS_SC_3 = "7205";

	public const string TREASURECHEST_BRONZE_BACKSCRATCHERS_BC_1 = "7206";

	public const string TREASURECHEST_BRONZE_DETECTIVEKOBOLD_BC_1 = "7207";

	public const string TREASURECHEST_BRONZE_SUCKEREDIN_BC_1 = "7208";

	public const string TREASURECHEST_BRONZE_PERFECTPARTY_BC_1 = "7209";

	public const string TREASURECHEST_BRONZE_PROVEFISHINGSKILLS_BC_1 = "7210";

	public const string TREASURECHEST_BRONZE_STATUEOFLIMITATIONS_BC_1 = "7211";

	public const string TREASURECHEST_BRONZE_BACKSCRATCHERS_BC_2 = "7212";

	public const string TREASURECHEST_BRONZE_BACKSCRATCHERS_BC_3 = "7213";

	public const string TREASURECHEST_BRONZE_BACKSCRATCHERS_BC_4 = "7214";

	public const string TREASURECHEST_BRONZE_BACKSCRATCHERS_BC_5 = "7215";

	public const string TREASURECHEST_BRONZE_DETECTIVEKOBOLD_BC_2 = "7216";

	public const string TREASURECHEST_BRONZE_DETECTIVEKOBOLD_BC_3 = "7217";

	public const string TREASURECHEST_BRONZE_DETECTIVEKOBOLD_BC_4 = "7218";

	public const string TREASURECHEST_BRONZE_DETECTIVEKOBOLD_BC_5 = "7219";

	public const string TREASURECHEST_BRONZE_SUCKEREDIN_BC_2 = "7220";

	public const string TREASURECHEST_BRONZE_SUCKEREDIN_BC_3 = "7221";

	public const string TREASURECHEST_BRONZE_SUCKEREDIN_BC_4 = "7222";

	public const string TREASURECHEST_BRONZE_SUCKEREDIN_BC_5 = "7223";

	public const string TREASURECHEST_BRONZE_PERFECTPARTY_BC_2 = "7224";

	public const string TREASURECHEST_BRONZE_PERFECTPARTY_BC_3 = "7225";

	public const string TREASURECHEST_BRONZE_PERFECTPARTY_BC_4 = "7226";

	public const string TREASURECHEST_BRONZE_PERFECTPARTY_BC_5 = "7227";

	public const string TREASURECHEST_BRONZE_PROVEFISHINGSKILLS_BC_2 = "7228";

	public const string TREASURECHEST_BRONZE_PROVEFISHINGSKILLS_BC_3 = "7229";

	public const string TREASURECHEST_BRONZE_PROVEFISHINGSKILLS_BC_4 = "7230";

	public const string TREASURECHEST_BRONZE_PROVEFISHINGSKILLS_BC_5 = "7231";

	public const string TREASURECHEST_BRONZE_STATUEOFLIMITATIONS_BC_2 = "7232";

	public const string TREASURECHEST_BRONZE_STATUEOFLIMITATIONS_BC_3 = "7233";

	public const string TREASURECHEST_BRONZE_STATUEOFLIMITATIONS_BC_4 = "7234";

	public const string TREASURECHEST_BRONZE_STATUEOFLIMITATIONS_BC_5 = "7235";

	public const string QUESTREWARD_PROVEFISHINGSKILLS = "7324";

	public const string QUESTREWARD_BACKSCRATCHERS = "7325";

	public const string QUESTREWARD_DETECTIVEKOBOLD = "7326";

	public const string QUESTREWARD_EVICTSUCKERS = "7327";

	public const string QUESTREWARD_STATUELIMITATIONS = "7328";

	public const string QUESTREWARD_HIKINGDISASTER = "7329";

	public const string QUESTREWARD_HAPPYBDAY = "7330";

	public const string ENIGMA_FERABIRDHOUSE = "7365";

	public const string ENIGMA_NETCHWEEDARMCHAIR_ = "7366";

	public const string TESTLOOT = "7398";

	public const string QUESTREWARD_BRENDASAWAKENING = "7977";

	public const string QUESTREWARD_AXEFAVOR = "7978";

	public const string QUESTREWARD_BUILDINGBRIDGES = "7979";

	public const string QUESTREWARD_CANDLELIGHTVIGIL = "7980";

	public const string QUESTREWARD_HATSANDHATNOTS = "7981";

	public const string QUESTREWARD_OVERANDOUT = "7982";

	public const string QUESTREWARD_STRAYPUPPIES = "7983";

	public const string QUESTREWARD_BLOODTUNDRA_QUEST1 = "7984";

	public const string TREASURECHEST_BRONZE_AXEFAVOR_BC_1 = "7985";

	public const string TREASURECHEST_BRONZE_AXEFAVOR_BC_2 = "7986";

	public const string TREASURECHEST_BRONZE_AXEFAVOR_BC_3 = "7987";

	public const string TREASURECHEST_BRONZE_AXEFAVOR_BC_4 = "7988";

	public const string TREASURECHEST_BRONZE_AXEFAVOR_BC_5 = "7989";

	public const string TREASURECHEST_SILVER_AXEFAVOR_SC_1 = "7990";

	public const string TREASURECHEST_SILVER_AXEFAVOR_SC_2 = "7991";

	public const string TREASURECHEST_SILVER_AXEFAVOR_SC_3 = "7992";

	public const string TREASURECHEST_GOLD_AXEFAVOR_GC_1 = "7993";

	public const string TREASURECHEST_GOLD_AXEFAVOR_GC_2 = "7994";

	public const string TREASURECHEST_BRONZE_BRENDASAWAKENING_BC_1 = "7995";

	public const string TREASURECHEST_BRONZE_BRENDASAWAKENING_BC_2 = "7996";

	public const string TREASURECHEST_BRONZE_BRENDASAWAKENING_BC_3 = "7997";

	public const string TREASURECHEST_BRONZE_BRENDASAWAKENING_BC_4 = "7998";

	public const string TREASURECHEST_BRONZE_BRENDASAWAKENING_BC_5 = "7999";

	public const string TREASURECHEST_SILVER_BRENDASAWAKENING_SC_1 = "8000";

	public const string TREASURECHEST_SILVER_BRENDASAWAKENING_SC_2 = "8001";

	public const string TREASURECHEST_SILVER_BRENDASAWAKENING_SC_3 = "8002";

	public const string TREASURECHEST_GOLD_BRENDASAWAKENING_GC_1 = "8003";

	public const string TREASURECHEST_GOLD_BRENDASAWAKENING_GC_2 = "8004";

	public const string TREASURECHEST_BRONZE_BUILDINGBRIDGES_BC_1 = "8005";

	public const string TREASURECHEST_BRONZE_BUILDINGBRIDGES_BC_2 = "8006";

	public const string TREASURECHEST_BRONZE_BUILDINGBRIDGES_BC_3 = "8007";

	public const string TREASURECHEST_BRONZE_BUILDINGBRIDGES_BC_4 = "8008";

	public const string TREASURECHEST_BRONZE_BUILDINGBRIDGES_BC_5 = "8009";

	public const string TREASURECHEST_SILVER_BUILDINGBRIDGES_SC_1 = "8010";

	public const string TREASURECHEST_SILVER_BUILDINGBRIDGES_SC_2 = "8011";

	public const string TREASURECHEST_SILVER_BUILDINGBRIDGES_SC_3 = "8012";

	public const string TREASURECHEST_GOLD_BUILDINGBRIDGES_GC_1 = "8013";

	public const string TREASURECHEST_GOLD_BUILDINGBRIDGES_GC_2 = "8014";

	public const string TREASURECHEST_BRONZE_CANDLELIGHTVIGIL_BC_1 = "8015";

	public const string TREASURECHEST_BRONZE_CANDLELIGHTVIGIL_BC_2 = "8016";

	public const string TREASURECHEST_BRONZE_CANDLELIGHTVIGIL_BC_3 = "8017";

	public const string TREASURECHEST_BRONZE_CANDLELIGHTVIGIL_BC_4 = "8018";

	public const string TREASURECHEST_BRONZE_CANDLELIGHTVIGIL_BC_5 = "8019";

	public const string TREASURECHEST_SILVER_CANDLELIGHTVIGIL_SC_1 = "8020";

	public const string TREASURECHEST_SILVER_CANDLELIGHTVIGIL_SC_2 = "8021";

	public const string TREASURECHEST_SILVER_CANDLELIGHTVIGIL_SC_3 = "8022";

	public const string TREASURECHEST_GOLD_CANDLELIGHTVIGIL_GC_1 = "8023";

	public const string TREASURECHEST_GOLD_CANDLELIGHTVIGIL_GC_2 = "8024";

	public const string TREASURECHEST_BRONZE_HATSANDHATNOTS_BC_1 = "8025";

	public const string TREASURECHEST_BRONZE_HATSANDHATNOTS_BC_2 = "8026";

	public const string TREASURECHEST_BRONZE_HATSANDHATNOTS_BC_3 = "8027";

	public const string TREASURECHEST_BRONZE_HATSANDHATNOTS_BC_4 = "8028";

	public const string TREASURECHEST_BRONZE_HATSANDHATNOTS_BC_5 = "8029";

	public const string TREASURECHEST_SILVER_HATSANDHATNOTS_SC_1 = "8030";

	public const string TREASURECHEST_SILVER_HATSANDHATNOTS_SC_2 = "8031";

	public const string TREASURECHEST_SILVER_HATSANDHATNOTS_SC_3 = "8032";

	public const string TREASURECHEST_GOLD_HATSANDHATNOTS_GC_1 = "8033";

	public const string TREASURECHEST_GOLD_HATSANDHATNOTS_GC_2 = "8034";

	public const string TREASURECHEST_BRONZE_OVERANDOUT_BC_1 = "8035";

	public const string TREASURECHEST_BRONZE_OVERANDOUT_BC_2 = "8036";

	public const string TREASURECHEST_BRONZE_OVERANDOUT_BC_3 = "8037";

	public const string TREASURECHEST_BRONZE_OVERANDOUT_BC_4 = "8038";

	public const string TREASURECHEST_BRONZE_OVERANDOUT_BC_5 = "8039";

	public const string TREASURECHEST_SILVER_OVERANDOUT_SC_1 = "8040";

	public const string TREASURECHEST_SILVER_OVERANDOUT_SC_2 = "8041";

	public const string TREASURECHEST_SILVER_OVERANDOUT_SC_3 = "8042";

	public const string TREASURECHEST_GOLD_OVERANDOUT_GC_1 = "8043";

	public const string TREASURECHEST_GOLD_OVERANDOUT_GC_2 = "8044";

	public const string TREASURECHEST_BRONZE_STRAYPUPPIES_BC_1 = "8047";

	public const string TREASURECHEST_BRONZE_STRAYPUPPIES_BC_2 = "8048";

	public const string TREASURECHEST_BRONZE_STRAYPUPPIES_BC_3 = "8050";

	public const string TREASURECHEST_BRONZE_STRAYPUPPIES_BC_4 = "8052";

	public const string TREASURECHEST_BRONZE_STRAYPUPPIES_BC_5 = "8053";

	public const string TREASURECHEST_SILVER_STRAYPUPPIES_SC_1 = "8055";

	public const string TREASURECHEST_SILVER_STRAYPUPPIES_SC_2 = "8058";

	public const string TREASURECHEST_SILVER_STRAYPUPPIES_SC_3 = "8060";

	public const string TREASURECHEST_GOLD_STRAYPUPPIES_GC_1 = "8062";

	public const string TREASURECHEST_GOLD_STRAYPUPPIES_GC_2 = "8064";

	public const string QUESTREWARD_SNAKES = "8185";

	public const string QUESTREWARD_COLLECTBONES = "8186";

	public const string TREASURECHEST_BRONZE_COLLECTBONES_BC_1 = "8466";

	public const string TREASURECHEST_BRONZE_COLLECTBONES_BC_2 = "8467";

	public const string TREASURECHEST_BRONZE_COLLECTBONES_BC_3 = "8468";

	public const string TREASURECHEST_BRONZE_COLLECTBONES_BC_4 = "8469";

	public const string TREASURECHEST_BRONZE_COLLECTBONES_BC_5 = "8470";

	public const string TREASURECHEST_SILVER_COLLECTBONES_SC_1 = "8471";

	public const string TREASURECHEST_SILVER_COLLECTBONES_SC_2 = "8472";

	public const string TREASURECHEST_SILVER_COLLECTBONES_SC_3 = "8473";

	public const string TREASURECHEST_GOLD_COLLECTBONES_GC_1 = "8474";

	public const string TREASURECHEST_GOLD_COLLECTBONES_GC_2 = "8475";

	public const string TREASURECHEST_BRONZE_LOSTPET_BC_1 = "8476";

	public const string TREASURECHEST_BRONZE_LOSTPET_BC_2 = "8477";

	public const string TREASURECHEST_BRONZE_LOSTPET_BC_3 = "8478";

	public const string TREASURECHEST_BRONZE_LOSTPET_BC_4 = "8479";

	public const string TREASURECHEST_BRONZE_LOSTPET_BC_5 = "8480";

	public const string TREASURECHEST_SILVER_LOSTPET_SC_1 = "8481";

	public const string TREASURECHEST_SILVER_LOSTPET_SC_2 = "8482";

	public const string TREASURECHEST_SILVER_LOSTPET_SC_3 = "8483";

	public const string TREASURECHEST_GOLD_LOSTPET_GC_1 = "8484";

	public const string TREASURECHEST_GOLD_LOSTPET_GC_2 = "8485";

	public const string TREASURECHEST_BRONZE_QUEST1_BC_1 = "8486";

	public const string TREASURECHEST_BRONZE_QUEST1_BC_2 = "8487";

	public const string TREASURECHEST_BRONZE_QUEST1_BC_3 = "8488";

	public const string TREASURECHEST_BRONZE_QUEST1_BC_4 = "8489";

	public const string TREASURECHEST_BRONZE_QUEST1_BC_5 = "8490";

	public const string TREASURECHEST_SILVER_QUEST1_SC_1 = "8491";

	public const string TREASURECHEST_SILVER_QUEST1_SC_2 = "8492";

	public const string TREASURECHEST_SILVER_QUEST1_SC_3 = "8493";

	public const string TREASURECHEST_GOLD_QUEST1_GC_1 = "8494";

	public const string TREASURECHEST_GOLD_QUEST1_GC_2 = "8495";

	public const string TREASURECHEST_BRONZE_SERIALCHILLER_BC_1 = "8496";

	public const string TREASURECHEST_BRONZE_SERIALCHILLER_BC_2 = "8497";

	public const string TREASURECHEST_BRONZE_SERIALCHILLER_BC_3 = "8498";

	public const string TREASURECHEST_BRONZE_SERIALCHILLER_BC_4 = "8499";

	public const string TREASURECHEST_BRONZE_SERIALCHILLER_BC_5 = "8500";

	public const string TREASURECHEST_SILVER_SERIALCHILLER_SC_1 = "8501";

	public const string TREASURECHEST_SILVER_SERIALCHILLER_SC_2 = "8502";

	public const string TREASURECHEST_SILVER_SERIALCHILLER_SC_3 = "8503";

	public const string TREASURECHEST_GOLD_SERIALCHILLER_GC_1 = "8504";

	public const string TREASURECHEST_GOLD_SERIALCHILLER_GC_2 = "8505";

	public const string TREASURECHEST_BRONZE_SNAKES_BC_1 = "8506";

	public const string TREASURECHEST_BRONZE_SNAKES_BC_2 = "8507";

	public const string TREASURECHEST_BRONZE_SNAKES_BC_3 = "8508";

	public const string TREASURECHEST_BRONZE_SNAKES_BC_4 = "8509";

	public const string TREASURECHEST_BRONZE_SNAKES_BC_5 = "8510";

	public const string TREASURECHEST_SILVER_SNAKES_SC_1 = "8511";

	public const string TREASURECHEST_SILVER_SNAKES_SC_2 = "8512";

	public const string TREASURECHEST_SILVER_SNAKES_SC_3 = "8513";

	public const string TREASURECHEST_GOLD_SNAKES_GC_1 = "8514";

	public const string TREASURECHEST_GOLD_SNAKES_GC_2 = "8515";

	public const string TREASURECHEST_BRONZE_TOBOGGANNIGHTMARE_BC_1 = "8516";

	public const string TREASURECHEST_BRONZE_TOBOGGANNIGHTMARE_BC_2 = "8517";

	public const string TREASURECHEST_BRONZE_TOBOGGANNIGHTMARE_BC_3 = "8518";

	public const string TREASURECHEST_BRONZE_TOBOGGANNIGHTMARE_BC_4 = "8519";

	public const string TREASURECHEST_BRONZE_TOBOGGANNIGHTMARE_BC_5 = "8520";

	public const string TREASURECHEST_SILVER_TOBOGGANNIGHTMARE_SC_1 = "8521";

	public const string TREASURECHEST_SILVER_TOBOGGANNIGHTMARE_SC_2 = "8522";

	public const string TREASURECHEST_SILVER_TOBOGGANNIGHTMARE_SC_3 = "8523";

	public const string TREASURECHEST_GOLD_TOBOGGANNIGHTMARE_GC_1 = "8524";

	public const string TREASURECHEST_GOLD_TOBOGGANNIGHTMARE_GC_2 = "8525";

	public const string TREASURECHEST_BRONZE_TUNDRAGHOST_BC_1 = "8526";

	public const string TREASURECHEST_BRONZE_TUNDRAGHOST_BC_2 = "8527";

	public const string TREASURECHEST_BRONZE_TUNDRAGHOST_BC_3 = "8528";

	public const string TREASURECHEST_BRONZE_TUNDRAGHOST_BC_4 = "8529";

	public const string TREASURECHEST_BRONZE_TUNDRAGHOST_BC_5 = "8530";

	public const string TREASURECHEST_SILVER_TUNDRAGHOST_SC_1 = "8531";

	public const string TREASURECHEST_SILVER_TUNDRAGHOST_SC_2 = "8532";

	public const string TREASURECHEST_SILVER_TUNDRAGHOST_SC_3 = "8533";

	public const string TREASURECHEST_GOLD_TUNDRAGHOST_GC_1 = "8534";

	public const string TREASURECHEST_GOLD_TUNDRAGHOST_GC_2 = "8535";

	public const string QUESTREWARD_SERIALCHILLER = "8536";

	public const string QUESTREWARD_LOSTPET = "8537";

	public const string QUESTREWARD_TUNDRAGHOST = "8538";

	public const string QUESTREWARD_SERIALCHILLERSECRETQUEST = "8539";

	public const string QUESTREWARD_TOBOGGANNIGHTMARE = "8632";

	public const string QUESTREWARD_SEARCHINGBONEPILES = "8638";

	public const string TREASURECHEST_BRONZE_SEARCHINGBONEPILES_BC_1 = "8639";

	public const string TREASURECHEST_BRONZE_SEARCHINGBONEPILES_BC_2 = "8640";

	public const string TREASURECHEST_BRONZE_SEARCHINGBONEPILES_BC_3 = "8641";

	public const string TREASURECHEST_BRONZE_SEARCHINGBONEPILES_BC_4 = "8642";

	public const string TREASURECHEST_BRONZE_SEARCHINGBONEPILES_BC_5 = "8643";

	public const string TREASURECHEST_SILVER_SEARCHINGBONEPILES_SC_1 = "8644";

	public const string TREASURECHEST_SILVER_SEARCHINGBONEPILES_SC_2 = "8645";

	public const string TREASURECHEST_SILVER_SEARCHINGBONEPILES_SC_3 = "8646";

	public const string TREASURECHEST_GOLD_SEARCHINGBONEPILES_GC_1 = "8647";

	public const string TREASURECHEST_GOLD_SEARCHINGBONEPILES_GC_2 = "8648";

	public const string TREASURECHEST_BRONZE_PETBLOODERFLY_BC_1 = "8714";

	public const string TREASURECHEST_BRONZE_PETBLOODERFLY_BC_2 = "8715";

	public const string TREASURECHEST_BRONZE_PETBLOODERFLY_BC_3 = "8716";

	public const string TREASURECHEST_BRONZE_PETBLOODERFLY_BC_4 = "8717";

	public const string TREASURECHEST_BRONZE_PETBLOODERFLY_BC_5 = "8718";

	public const string TREASURECHEST_SILVER_PETBLOODERFLY_SC_1 = "8719";

	public const string TREASURECHEST_SILVER_PETBLOODERFLY_SC_2 = "8720";

	public const string TREASURECHEST_SILVER_PETBLOODERFLY_SC_3 = "8721";

	public const string TREASURECHEST_GOLD_PETBLOODERFLY_GC_1 = "8722";

	public const string TREASURECHEST_GOLD_PETBLOODERFLY_GC_2 = "8723";

	public const string QUESTREWARD_PETBLOODERFLY = "8724";

	public const string QUESTREWARD_PETBLOODERFLYSECRETQUEST = "8730";

	public const string TREASURECHEST_REWARDLIST_COMMONINGREDIENTS = "10521";

	public const string TREASURECHEST_REWARDLIST_UNCOMMONINGREDIENTS = "10522";

	public const string TREASURECHEST_REWARDLIST_RAREINGREDIENTS = "10523";

	public const string TREASURECHEST_REWARDLIST_LIKES = "10524";

	public const string QUESTREWARD_WIZARDTRIALS = "11750";

	public const string QUESTREWARD_SOUPOFRIDDLES = "11751";

	public const string TREASURECHEST_BRONZE_WIZARDTRIALS_BC_1 = "11752";

	public const string TREASURECHEST_BRONZE_WIZARDTRIALS_BC_2 = "11753";

	public const string TREASURECHEST_BRONZE_WIZARDTRIALS_BC_3 = "11754";

	public const string TREASURECHEST_BRONZE_WIZARDTRIALS_BC_4 = "11755";

	public const string TREASURECHEST_BRONZE_WIZARDTRIALS_BC_5 = "11756";

	public const string TREASURECHEST_SILVER_WIZARDTRIALS_SC_1 = "11757";

	public const string TREASURECHEST_SILVER_WIZARDTRIALS_SC_2 = "11758";

	public const string TREASURECHEST_SILVER_WIZARDTRIALS_SC_3 = "11759";

	public const string TREASURECHEST_GOLD_WIZARDTRIALS_GC_1 = "11760";

	public const string TREASURECHEST_GOLD_WIZARDTRIALS_GC_2 = "11761";

	public const string TREASURECHEST_BRONZE_SOUPOFRIDDLES_BC_1 = "11762";

	public const string TREASURECHEST_BRONZE_SOUPOFRIDDLES_BC_2 = "11763";

	public const string TREASURECHEST_BRONZE_SOUPOFRIDDLES_BC_3 = "11764";

	public const string TREASURECHEST_BRONZE_SOUPOFRIDDLES_BC_4 = "11765";

	public const string TREASURECHEST_BRONZE_SOUPOFRIDDLES_BC_5 = "11766";

	public const string TREASURECHEST_SILVER_SOUPOFRIDDLES_SC_2 = "11767";

	public const string TREASURECHEST_SILVER_SOUPOFRIDDLES_SC_1 = "11768";

	public const string TREASURECHEST_SILVER_SOUPOFRIDDLES_SC_3 = "11769";

	public const string TREASURECHEST_GOLD_SOUPOFRIDDLES_GC_1 = "11770";

	public const string TREASURECHEST_GOLD_SOUPOFRIDDLES_GC_2 = "11771";

	public const string TREASURECHEST_BRONZE_HIGHANDDRY_BC_1 = "11861";

	public const string TREASURECHEST_BRONZE_HIGHANDDRY_BC_2 = "11862";

	public const string TREASURECHEST_BRONZE_HIGHANDDRY_BC_3 = "11863";

	public const string TREASURECHEST_BRONZE_HIGHANDDRY_BC_4 = "11864";

	public const string TREASURECHEST_BRONZE_HIGHANDDRY_BC_5 = "11865";

	public const string TREASURECHEST_SILVER_HIGHANDDRY_SC_1 = "11866";

	public const string TREASURECHEST_SILVER_HIGHANDDRY_SC_2 = "11867";

	public const string TREASURECHEST_SILVER_HIGHANDDRY_SC_3 = "11868";

	public const string TREASURECHEST_GOLD_HIGHANDDRY_GC_1 = "11869";

	public const string TREASURECHEST_GOLD_HIGHANDDRY_GC_2 = "11870";

	public const string QUESTREWARD_HIGHANDDRY = "11871";

	public const string QUESTREWARD_MYREFOLKSNEWCLOTHES = "11984";

	public const string TREASURECHEST_BRONZE_MYREFOLKSNEWCLOTHES_BC_1 = "11994";

	public const string TREASURECHEST_BRONZE_MYREFOLKSNEWCLOTHES_BC_2 = "11995";

	public const string TREASURECHEST_BRONZE_MYREFOLKSNEWCLOTHES_BC_3 = "11996";

	public const string TREASURECHEST_BRONZE_MYREFOLKSNEWCLOTHES_BC_4 = "11997";

	public const string TREASURECHEST_BRONZE_MYREFOLKSNEWCLOTHES_BC_5 = "11998";

	public const string TREASURECHEST_GOLD_MYREFOLKSNEWCLOTHES_GC_1 = "11999";

	public const string TREASURECHEST_GOLD_MYREFOLKSNEWCLOTHES_GC_2 = "12000";

	public const string TREASURECHEST_SILVER_MYREFOLKSNEWCLOTHES_SC_1 = "12001";

	public const string TREASURECHEST_SILVER_MYREFOLKSNEWCLOTHES_SC_2 = "12002";

	public const string TREASURECHEST_SILVER_MYREFOLKSNEWCLOTHES_SC_3 = "12003";

	public const string QUESTREWARD_STICKYSITUATION = "12007";

	public const string TREASURECHEST_BRONZE_STICKYSITUATION_BC_1 = "12008";

	public const string TREASURECHEST_BRONZE_STICKYSITUATION_BC_2 = "12009";

	public const string TREASURECHEST_BRONZE_STICKYSITUATION_BC_3 = "12010";

	public const string TREASURECHEST_BRONZE_STICKYSITUATION_BC_4 = "12011";

	public const string TREASURECHEST_BRONZE_STICKYSITUATION_BC_5 = "12012";

	public const string TREASURECHEST_GOLD_STICKYSITUATION_GC_1 = "12013";

	public const string TREASURECHEST_GOLD_STICKYSITUATION_GC_2 = "12014";

	public const string TREASURECHEST_SILVER_STICKYSITUATION_SC_1 = "12015";

	public const string TREASURECHEST_SILVER_STICKYSITUATION_SC_2 = "12016";

	public const string TREASURECHEST_SILVER_STICKYSITUATION_SC_3 = "12017";

	public const string TREASURECHEST_BRONZE_PICKENHUNT_BC_1 = "12247";

	public const string TREASURECHEST_BRONZE_PICKENHUNT_BC_2 = "12248";

	public const string TREASURECHEST_BRONZE_PICKENHUNT_BC_3 = "12249";

	public const string TREASURECHEST_BRONZE_PICKENHUNT_BC_4 = "12250";

	public const string TREASURECHEST_BRONZE_PICKENHUNT_BC_5 = "12251";

	public const string TREASURECHEST_SILVER_PICKENHUNT_SC_1 = "12252";

	public const string TREASURECHEST_SILVER_PICKENHUNT_SC_2 = "12253";

	public const string TREASURECHEST_SILVER_PICKENHUNT_SC_3 = "12254";

	public const string TREASURECHEST_GOLD_PICKENHUNT_GC_1 = "12255";

	public const string TREASURECHEST_GOLD_PICKENHUNT_GC_2 = "12256";

	public const string TREASURECHEST_BRONZE_HERMITCOLLECT_BC_1 = "12257";

	public const string TREASURECHEST_BRONZE_HERMITCOLLECT_BC_2 = "12258";

	public const string TREASURECHEST_BRONZE_HERMITCOLLECT_BC_3 = "12259";

	public const string TREASURECHEST_BRONZE_HERMITCOLLECT_BC_4 = "12260";

	public const string TREASURECHEST_BRONZE_HERMITCOLLECT_BC_5 = "12261";

	public const string TREASURECHEST_SILVER_HERMITCOLLECT_SC_1 = "12262";

	public const string TREASURECHEST_SILVER_HERMITCOLLECT_SC_2 = "12263";

	public const string TREASURECHEST_SILVER_HERMITCOLLECT_SC_3 = "12264";

	public const string TREASURECHEST_GOLD_HERMITCOLLECT_GC_1 = "12265";

	public const string TREASURECHEST_GOLD_HERMITCOLLECT_GC_2 = "12266";

	public const string TREASURECHEST_BRONZE_SCRATCHTREES_BC_1 = "12267";

	public const string TREASURECHEST_BRONZE_SCRATCHTREES_BC_2 = "12268";

	public const string TREASURECHEST_BRONZE_SCRATCHTREES_BC_3 = "12269";

	public const string TREASURECHEST_BRONZE_SCRATCHTREES_BC_4 = "12270";

	public const string TREASURECHEST_BRONZE_SCRATCHTREES_BC_5 = "12271";

	public const string TREASURECHEST_SILVER_SCRATCHTREES_SC_1 = "12272";

	public const string TREASURECHEST_SILVER_SCRATCHTREES_SC_2 = "12273";

	public const string TREASURECHEST_SILVER_SCRATCHTREES_SC_3 = "12274";

	public const string TREASURECHEST_GOLD_SCRATCHTREES_GC_1 = "12275";

	public const string TREASURECHEST_GOLD_SCRATCHTREES_GC_2 = "12276";

	public const string QUESTREWARD_PICKENHUNT = "12285";

	public const string QUESTREWARD_SCRATCHTREES = "12286";

	public const string QUESTREWARD_HERMITCOLLECT = "12287";

	public const string TREASURECHEST_BRONZE_PIZZADELIVERY_BC_1 = "12367";

	public const string TREASURECHEST_BRONZE_PIZZADELIVERY_BC_2 = "12368";

	public const string TREASURECHEST_BRONZE_PIZZADELIVERY_BC_3 = "12369";

	public const string TREASURECHEST_BRONZE_PIZZADELIVERY_BC_4 = "12370";

	public const string TREASURECHEST_BRONZE_PIZZADELIVERY_BC_5 = "12371";

	public const string TREASURECHEST_SILVER_PIZZADELIVERY_SC_1 = "12372";

	public const string TREASURECHEST_SILVER_PIZZADELIVERY_SC_2 = "12373";

	public const string TREASURECHEST_SILVER_PIZZADELIVERY_SC_3 = "12374";

	public const string TREASURECHEST_GOLD_PIZZADELIVERY_GC_1 = "12375";

	public const string TREASURECHEST_GOLD_PIZZADELIVERY_GC_2 = "12376";

	public const string QUESTREWARD_PIZZADELIVERY = "12377";

	public const string QUESTREWARD_LOCUSTINFESTATION = "12405";

	public const string TREASURECHEST_BRONZE_LOCUSTINFESTATION_BC_1 = "12406";

	public const string TREASURECHEST_BRONZE_LOCUSTINFESTATION_BC_2 = "12407";

	public const string TREASURECHEST_BRONZE_LOCUSTINFESTATION_BC_3 = "12408";

	public const string TREASURECHEST_BRONZE_LOCUSTINFESTATION_BC_4 = "12409";

	public const string TREASURECHEST_BRONZE_LOCUSTINFESTATION_BC_5 = "12410";

	public const string TREASURECHEST_GOLD_LOCUSTINFESTATION_GC_1 = "12411";

	public const string TREASURECHEST_GOLD_LOCUSTINFESTATION_GC_2 = "12412";

	public const string TREASURECHEST_SILVER_LOCUSTINFESTATION_SC_1 = "12413";

	public const string TREASURECHEST_SILVER_LOCUSTINFESTATION_SC_2 = "12414";

	public const string TREASURECHEST_SILVER_LOCUSTINFESTATION_SC_3 = "12415";

	public const string QUESTREWARD_WASHEDUP = "13076";

	public const string TREASURECHEST_BRONZE_WASHEDUP_BC_1 = "13077";

	public const string TREASURECHEST_BRONZE_WASHEDUP_BC_2 = "13078";

	public const string TREASURECHEST_BRONZE_WASHEDUP_BC_3 = "13079";

	public const string TREASURECHEST_BRONZE_WASHEDUP_BC_4 = "13080";

	public const string TREASURECHEST_BRONZE_WASHEDUP_BC_5 = "13081";

	public const string TREASURECHEST_GOLD_WASHEDUP_GC_1 = "13082";

	public const string TREASURECHEST_GOLD_WASHEDUP_GC_2 = "13083";

	public const string TREASURECHEST_SILVER_WASHEDUP_SC_1 = "13084";

	public const string TREASURECHEST_SILVER_WASHEDUP_SC_2 = "13085";

	public const string TREASURECHEST_SILVER_WASHEDUP_SC_3 = "13086";

	public const string CASUALGAME_MATCH3_PORTRAIT1 = "13384";

	public const string CASUALGAME_MATCH3_PORTRAIT2 = "13385";

	public const string CASUALGAME_MATCH3_PORTRAIT3 = "13386";

	public const string CASUALGAME_MATCH3_PORTRAIT4 = "13387";

	public const string CASUALGAME_MATCH3_PORTRAIT5 = "13388";

	public const string CASUALGAME_MATCH3_PORTRAIT6 = "13389";

	public const string ENIGMA_CRAGFENCE = "13544";

	public const string CASUALGAME_MATCH3_LEVELS1_25 = "13625";

	public const string CASUALGAME_MATCH3_LEVELS26_50 = "13626";

	public const string CASUALGAME_MATCH3_LEVELS51_100 = "13627";

	public const string CASUALGAME_MATCH3_LEVELS36_45REUSE = "13628";

	public const string CASUALGAME_MATCH3_REWARDS_LIKES = "13629";

	public const string CASUALGAME_MATCH3_LEVELS61_100REUSE = "13630";

	public const string CASUALGAME_MATCH3_LEVELS100UP = "13631";

	public const string CASUALGAME_MATCH3_LEVELS151_300REUSE = "13632";

	public const string CASUALGAME_COMMON_LIKES300 = "13633";

	public const string CASUALGAME_COMMON_LIKES500 = "13634";

	public const string CASUALGAME_MATCH3_REWARDS_COMMONINGREDIENTS = "13635";

	public const string CASUALGAME_MATCH3_REWARDS_UNCOMMONINGREDIENTS = "13636";

	public const string CASUALGAME_MATCH3_REWARDS_RAREINGREDIENTS = "13637";

	public const string CASUALGAME_MATCH3_REWARDS_CLOTHINGALL = "13638";

	public const string CASUALGAME_MATCH3_REWARDS_TIER2CLOTHING = "13639";

	public const string CASUALGAME_MATCH3_REWARDS_TIER3CLOTHING = "13640";

	public const string QUESTREWARD_SEAGULLS = "13747";

	public const string TREASURECHEST_BRONZE_SEAGULLS_BC_1 = "13748";

	public const string TREASURECHEST_BRONZE_SEAGULLS_BC_2 = "13749";

	public const string TREASURECHEST_BRONZE_SEAGULLS_BC_3 = "13750";

	public const string TREASURECHEST_BRONZE_SEAGULLS_BC_4 = "13751";

	public const string TREASURECHEST_BRONZE_SEAGULLS_BC_5 = "13752";

	public const string TREASURECHEST_SILVER_SEAGULLS_SC_1 = "13753";

	public const string TREASURECHEST_SILVER_SEAGULLS_SC_2 = "13754";

	public const string TREASURECHEST_SILVER_SEAGULLS_SC_3 = "13755";

	public const string TREASURECHEST_GOLD_SEAGULLS_GC_1 = "13756";

	public const string TREASURECHEST_GOLD_SEAGULLS_GC_2 = "13757";

	public const string QUESTREWARD_STATUEREPAIR = "13781";

	public const string TREASURECHEST_BRONZE_STATUEREPAIR_BC_1 = "13783";

	public const string TREASURECHEST_BRONZE_STATUEREPAIR_BC_2 = "13784";

	public const string TREASURECHEST_BRONZE_STATUEREPAIR_BC_3 = "13785";

	public const string TREASURECHEST_BRONZE_STATUEREPAIR_BC_4 = "13786";

	public const string TREASURECHEST_BRONZE_STATUEREPAIR_BC_5 = "13787";

	public const string TREASURECHEST_SILVER_STATUEREPAIR_SC_1 = "13788";

	public const string TREASURECHEST_SILVER_STATUEREPAIR_SC_2 = "13789";

	public const string TREASURECHEST_GOLD_STATUEREPAIR_GC_1 = "13790";

	public const string TREASURECHEST_SILVER_STATUEREPAIR_SC_3 = "13791";

	public const string TREASURECHEST_GOLD_STATUEREPAIR_GC_2 = "13792";

	public const string QUESTREWARD_BRODYRACE = "13913";

	public const string TREASURECHEST_BRONZE_BRODYRACE_BC_1 = "13914";

	public const string TREASURECHEST_BRONZE_BRODYRACE_BC_2 = "13915";

	public const string TREASURECHEST_BRONZE_BRODYRACE_BC_3 = "13916";

	public const string TREASURECHEST_BRONZE_BRODYRACE_BC_4 = "13917";

	public const string TREASURECHEST_BRONZE_BRODYRACE_BC_5 = "13918";

	public const string TREASURECHEST_SILVER_BRODYRACE_SC_1 = "13919";

	public const string TREASURECHEST_SILVER_BRODYRACE_SC_2 = "13920";

	public const string TREASURECHEST_SILVER_BRODYRACE_SC_3 = "13921";

	public const string TREASURECHEST_GOLD_BRODYRACE_GC_1 = "13922";

	public const string TREASURECHEST_GOLD_BRODYRACE_GC_2 = "13923";

	public const string QUESTREWARD_ZOMBOLDAPOCALYPSE = "13988";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE_BC_1 = "13989";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE_BC_2 = "13990";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE_BC_3 = "13991";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE_BC_4 = "13992";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE_BC_5 = "13993";

	public const string TREASURECHEST_SILVER_ZOMBOLDAPOCALYPSE_SC_1 = "13994";

	public const string TREASURECHEST_SILVER_ZOMBOLDAPOCALYPSE_SC_2 = "13995";

	public const string TREASURECHEST_SILVER_ZOMBOLDAPOCALYPSE_SC_3 = "13996";

	public const string TREASURECHEST_GOLD_ZOMBOLDAPOCALYPSE_GC_1 = "13997";

	public const string TREASURECHEST_GOLD_ZOMBOLDAPOCALYPSE_GC_2 = "13998";

	public const string QUESTREWARD_BOUQUETOFBELLS = "14019";

	public const string TREASURECHEST_BRONZE_BOUQUETOFBELLS_BC_1 = "14020";

	public const string TREASURECHEST_BRONZE_BOUQUETOFBELLS_BC_2 = "14021";

	public const string TREASURECHEST_BRONZE_BOUQUETOFBELLS_BC_3 = "14022";

	public const string TREASURECHEST_BRONZE_BOUQUETOFBELLS_BC_4 = "14023";

	public const string TREASURECHEST_BRONZE_BOUQUETOFBELLS_BC_5 = "14024";

	public const string TREASURECHEST_SILVER_BOUQUETOFBELLS_SC_1 = "14025";

	public const string TREASURECHEST_SILVER_BOUQUETOFBELLS_SC_2 = "14026";

	public const string TREASURECHEST_SILVER_BOUQUETOFBELLS_SC_3 = "14027";

	public const string TREASURECHEST_GOLD_BOUQUETOFBELLS_GC_1 = "14028";

	public const string TREASURECHEST_GOLD_BOUQUETOFBELLS_GC_2 = "14029";

	public const string QUESTREWARD_GLASSEYE = "14037";

	public const string TREASURECHEST_BRONZE_GLASSEYE_BC_1 = "14038";

	public const string TREASURECHEST_BRONZE_GLASSEYE_BC_2 = "14039";

	public const string TREASURECHEST_BRONZE_GLASSEYE_BC_3 = "14040";

	public const string TREASURECHEST_BRONZE_GLASSEYE_BC_4 = "14041";

	public const string TREASURECHEST_BRONZE_GLASSEYE_BC_5 = "14042";

	public const string TREASURECHEST_SILVER_GLASSEYE_SC_1 = "14043";

	public const string TREASURECHEST_SILVER_GLASSEYE_SC_2 = "14044";

	public const string TREASURECHEST_SILVER_GLASSEYE_SC_3 = "14045";

	public const string TREASURECHEST_GOLD_GLASSEYE_GC_1 = "14046";

	public const string TREASURECHEST_GOLD_GLASSEYE_GC_2 = "14047";

	public const string QUESTREWARD_PIZZADRONES = "14067";

	public const string TREASURECHEST_BRONZE_PIZZADRONES_BC_1 = "14068";

	public const string TREASURECHEST_BRONZE_PIZZADRONES_BC_2 = "14069";

	public const string TREASURECHEST_BRONZE_PIZZADRONES_BC_3 = "14070";

	public const string TREASURECHEST_BRONZE_PIZZADRONES_BC_4 = "14071";

	public const string TREASURECHEST_BRONZE_PIZZADRONES_BC_5 = "14072";

	public const string TREASURECHEST_SILVER_PIZZADRONES_SC_1 = "14073";

	public const string TREASURECHEST_SILVER_PIZZADRONES_SC_2 = "14074";

	public const string TREASURECHEST_SILVER_PIZZADRONES_SC_3 = "14075";

	public const string TREASURECHEST_GOLD_PIZZADRONES_GC_1 = "14076";

	public const string TREASURECHEST_GOLD_PIZZADRONES_GC_2 = "14077";

	public const string TREASURECHEST_SILVER_CAPTAINCLUCK_SC_3 = "14146";

	public const string TREASURECHEST_SILVER_CAPTAINCLUCK_SC_2 = "14147";

	public const string TREASURECHEST_SILVER_CAPTAINCLUCK_SC_1 = "14148";

	public const string TREASURECHEST_GOLD_CAPTAINCLUCK_GC_2 = "14149";

	public const string TREASURECHEST_GOLD_CAPTAINCLUCK_GC_1 = "14150";

	public const string TREASURECHEST_BRONZE_CAPTAINCLUCK_BC_5 = "14151";

	public const string TREASURECHEST_BRONZE_CAPTAINCLUCK_BC_4 = "14152";

	public const string TREASURECHEST_BRONZE_CAPTAINCLUCK_BC_3 = "14153";

	public const string TREASURECHEST_BRONZE_CAPTAINCLUCK_BC_2 = "14154";

	public const string TREASURECHEST_BRONZE_CAPTAINCLUCK_BC_1 = "14155";

	public const string QUESTREWARD_CAPTAINCLUCK = "14156";

	public const string QUESTREWARD_TIMEFORSOMEGRUB = "14157";

	public const string TREASURECHEST_BRONZE_TIMEFORSOMEGRUB_BC_1 = "14158";

	public const string TREASURECHEST_BRONZE_TIMEFORSOMEGRUB_BC_2 = "14159";

	public const string TREASURECHEST_BRONZE_TIMEFORSOMEGRUB_BC_3 = "14160";

	public const string TREASURECHEST_BRONZE_TIMEFORSOMEGRUB_BC_4 = "14161";

	public const string TREASURECHEST_BRONZE_TIMEFORSOMEGRUB_BC_5 = "14162";

	public const string TREASURECHEST_SILVER_TIMEFORSOMEGRUB_SC_1 = "14163";

	public const string TREASURECHEST_SILVER_TIMEFORSOMEGRUB_SC_2 = "14164";

	public const string TREASURECHEST_GOLD_TIMEFORSOMEGRUB_GC_1 = "14165";

	public const string TREASURECHEST_SILVER_TIMEFORSOMEGRUB_SC_3 = "14166";

	public const string TREASURECHEST_GOLD_TIMEFORSOMEGRUB_GC_2 = "14167";

	public const string TREASURECHEST_BRONZE_HATSBIGDAY_BC_1 = "14186";

	public const string TREASURECHEST_BRONZE_HATSBIGDAY_BC_2 = "14187";

	public const string TREASURECHEST_BRONZE_HATSBIGDAY_BC_3 = "14188";

	public const string TREASURECHEST_BRONZE_HATSBIGDAY_BC_4 = "14189";

	public const string TREASURECHEST_BRONZE_HATSBIGDAY_BC_5 = "14190";

	public const string TREASURECHEST_SILVER_HATSBIGDAY_SC_1 = "14191";

	public const string TREASURECHEST_SILVER_HATSBIGDAY_SC_2 = "14192";

	public const string TREASURECHEST_SILVER_HATSBIGDAY_SC_3 = "14193";

	public const string TREASURECHEST_GOLD_HATSBIGDAY_GC_1 = "14194";

	public const string TREASURECHEST_GOLD_HATSBIGDAY_GC_2 = "14195";

	public const string QUESTREWARD_HATSBIGDAY = "14196";

	public const string TREASURECHEST_BRONZE_PANTSSEQUEL_BC_1 = "14233";

	public const string TREASURECHEST_BRONZE_PANTSSEQUEL_BC_2 = "14234";

	public const string TREASURECHEST_BRONZE_PANTSSEQUEL_BC_3 = "14235";

	public const string TREASURECHEST_BRONZE_PANTSSEQUEL_BC_4 = "14236";

	public const string TREASURECHEST_BRONZE_PANTSSEQUEL_BC_5 = "14237";

	public const string TREASURECHEST_SILVER_PANTSSEQUEL_SC_1 = "14238";

	public const string TREASURECHEST_SILVER_PANTSSEQUEL_SC_2 = "14240";

	public const string TREASURECHEST_SILVER_PANTSSEQUEL_SC_3 = "14241";

	public const string TREASURECHEST_GOLD_PANTSSEQUEL_GC_1 = "14242";

	public const string TREASURECHEST_GOLD_PANTSSEQUEL_GC_2 = "14243";

	public const string QUESTREWARD_PANTSSEQUEL = "14244";

	public const string QUESTREWARD_WASHEDUPBONUS = "15022";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_PIZZADRONES = "15063";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_LOCUSTINFESTATION = "15064";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_STATUEREPAIR = "15065";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_TIMEFORSOMEGRUB = "15066";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_BOQUETOFBELLS = "15067";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_GLASSEYE = "15068";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_SCRATCHTREES = "15069";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_BRODYRACE = "15070";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_SEAGULLS = "15071";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_HATSBIGDAY = "15072";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_HERMITCOLLECT = "15073";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_WASHEDUP = "15074";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_CAPTAINCLUCK = "15075";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_PANTSSEQUEL = "15076";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_ZOMBOLDAPOCALYPSE = "15077";

	public const string QUESTREWARD_FOGPLANT = "15111";

	public const string TREASURECHEST_BRONZE_FOGPLANT_BC_1 = "15112";

	public const string TREASURECHEST_BRONZE_FOGPLANT_BC_2 = "15113";

	public const string TREASURECHEST_BRONZE_FOGPLANT_BC_3 = "15114";

	public const string TREASURECHEST_BRONZE_FOGPLANT_BC_4 = "15115";

	public const string TREASURECHEST_BRONZE_FOGPLANT_BC_5 = "15116";

	public const string TREASURECHEST_SILVER_FOGPLANT_SC_1 = "15117";

	public const string TREASURECHEST_SILVER_FOGPLANT_SC_2 = "15118";

	public const string TREASURECHEST_SILVER_FOGPLANT_SC_3 = "15119";

	public const string TREASURECHEST_GOLD_FOGPLANT_GC_1 = "15120";

	public const string TREASURECHEST_GOLD_FOGPLANT_GC_2 = "15121";

	public const string QUESTREWARD_ZOMBOLDAPOCALYPSE2 = "15187";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE2_BC_1 = "15188";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE2_BC_2 = "15189";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE2_BC_3 = "15190";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE2_BC_4 = "15191";

	public const string TREASURECHEST_BRONZE_ZOMBOLDAPOCALYPSE2_BC_5 = "15192";

	public const string TREASURECHEST_SILVER_ZOMBOLDAPOCALYPSE2_SC_1 = "15193";

	public const string TREASURECHEST_SILVER_ZOMBOLDAPOCALYPSE2_SC_2 = "15194";

	public const string TREASURECHEST_SILVER_ZOMBOLDAPOCALYPSE2_SC_3 = "15195";

	public const string TREASURECHEST_GOLD_ZOMBOLDAPOCALYPSE2_GC_1 = "15196";

	public const string TREASURECHEST_GOLD_ZOMBOLDAPOCALYPSE2_GC_2 = "15197";

	public const string QUESTREWARD_ETERNALSTENCH = "15328";

	public const string TREASURECHEST_BRONZE_ETERNALSTENCH_BC_1 = "15329";

	public const string TREASURECHEST_BRONZE_ETERNALSTENCH_BC_2 = "15330";

	public const string TREASURECHEST_BRONZE_ETERNALSTENCH_BC_3 = "15331";

	public const string TREASURECHEST_BRONZE_ETERNALSTENCH_BC_4 = "15332";

	public const string TREASURECHEST_BRONZE_ETERNALSTENCH_BC_5 = "15333";

	public const string TREASURECHEST_SILVER_ETERNALSTENCH_SC_1 = "15334";

	public const string TREASURECHEST_SILVER_ETERNALSTENCH_SC_2 = "15335";

	public const string TREASURECHEST_SILVER_ETERNALSTENCH_SC_3 = "15336";

	public const string TREASURECHEST_GOLD_ETERNALSTENCH_GC_1 = "15337";

	public const string TREASURECHEST_GOLD_ETERNALSTENCH_GC_2 = "15338";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_ETERNALSTENCH = "15635";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_FOGPLANT = "15636";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_ZOMBOLDAPOCALYPSE2 = "15637";

	public const string QUESTREWARD_MAKINGAMURDER = "15648";

	public const string TREASURECHEST_BRONZE_MAKINGAMURDER_BC_1 = "15649";

	public const string TREASURECHEST_BRONZE_MAKINGAMURDER_BC_2 = "15650";

	public const string TREASURECHEST_BRONZE_MAKINGAMURDER_BC_3 = "15651";

	public const string TREASURECHEST_BRONZE_MAKINGAMURDER_BC_4 = "15652";

	public const string TREASURECHEST_BRONZE_MAKINGAMURDER_BC_5 = "15653";

	public const string TREASURECHEST_SILVER_MAKINGAMURDER_SC_1 = "15654";

	public const string TREASURECHEST_SILVER_MAKINGAMURDER_SC_2 = "15655";

	public const string TREASURECHEST_SILVER_MAKINGAMURDER_SC_3 = "15656";

	public const string TREASURECHEST_GOLD_MAKINGAMURDER_GC_1 = "15657";

	public const string TREASURECHEST_GOLD_MAKINGAMURDER_GC_2 = "15658";

	public const string QUESTREWARD_JEDITRAINING = "15735";

	public const string TREASURECHEST_BRONZE_JEDITRAINING_BC_1 = "15737";

	public const string TREASURECHEST_BRONZE_JEDITRAINING_BC_2 = "15739";

	public const string TREASURECHEST_BRONZE_JEDITRAINING_BC_3 = "15740";

	public const string TREASURECHEST_BRONZE_JEDITRAINING_BC_4 = "15742";

	public const string TREASURECHEST_BRONZE_JEDITRAINING_BC_5 = "15743";

	public const string TREASURECHEST_SILVER_JEDITRAINING_SC_1 = "15744";

	public const string TREASURECHEST_SILVER_JEDITRAINING_SC_2 = "15745";

	public const string TREASURECHEST_SILVER_JEDITRAINING_SC_3 = "15747";

	public const string TREASURECHEST_GOLD_JEDITRAINING_GC_1 = "15748";

	public const string TREASURECHEST_GOLD_JEDITRAINING_GC_2 = "15749";

	public const string EMERGENTGAMEPLAY_DIGSPOT_DEFAULT = "15782";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_REWARDSLIST = "15798";

	public const string EMERGENTGAMEPLAY_DIGSPOT_REWARDSLIST = "15799";

	public const string EMERGENTGAMEPLAY_DIGSPOT_REWARDS_UNCOMMONINGREDIENTS = "15800";

	public const string EMERGENTGAMEPLAY_DIGSPOT_REWARDS_RAREINGREDIENTS = "15801";

	public const string EMERGENTGAMEPLAY_DIGSPOT_REWARDS_COMMONINGREDIENTS = "15802";

	public const string EMERGENTGAMEPLAY_DIGSPOT_REWARDS_CLOTHING = "15803";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_REWARDS_CLOTHING = "15804";

	public const string QUESTREWARD_DAILYQUESTS_FEEDTHEBLOODTREE = "15805";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_REWARDS_COMMONINGREDIENTS = "15806";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_REWARDS_RAREINGREDIENTS = "15808";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_REWARDS_UNCOMMONINGREDIENTS = "15809";

	public const string QUESTREWARD_DAILYQUESTS_REWARDS_DYELIST = "15810";

	public const string QUESTREWARD_DAILYQUESTS_REWARDS_CLOTHINGANDFURNITURE = "15811";

	public const string QUESTREWARD_DAILYQUESTS_REWARDS_REUSE = "15812";

	public const string QUESTREWARD_DAILYQUESTS_REWARDS_LOOTTABLE = "15813";

	public const string QUESTREWARD_KARENUNHINGED = "15875";

	public const string TREASURECHEST_BRONZE_KARENUNHINGED_BC_1 = "15876";

	public const string TREASURECHEST_BRONZE_KARENUNHINGED_BC_2 = "15877";

	public const string TREASURECHEST_BRONZE_KARENUNHINGED_BC_3 = "15878";

	public const string TREASURECHEST_BRONZE_KARENUNHINGED_BC_4 = "15879";

	public const string TREASURECHEST_BRONZE_KARENUNHINGED_BC_5 = "15880";

	public const string TREASURECHEST_SILVER_KARENUNHINGED_SC_1 = "15881";

	public const string TREASURECHEST_SILVER_KARENUNHINGED_SC_2 = "15882";

	public const string TREASURECHEST_SILVER_KARENUNHINGED_SC_3 = "15883";

	public const string TREASURECHEST_GOLD_KARENUNHINGED_GC_1 = "15884";

	public const string TREASURECHEST_GOLD_KARENUNHINGED_GC_2 = "15885";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_KARENUNHINGED = "15886";

	public const string QUESTREWARD_STRANGEMAGIC = "15970";

	public const string TREASURECHEST_BRONZE_STRANGEMAGIC_BC_1 = "15971";

	public const string TREASURECHEST_BRONZE_STRANGEMAGIC_BC_2 = "15972";

	public const string TREASURECHEST_BRONZE_STRANGEMAGIC_BC_3 = "15973";

	public const string TREASURECHEST_BRONZE_STRANGEMAGIC_BC_4 = "15974";

	public const string TREASURECHEST_BRONZE_STRANGEMAGIC_BC_5 = "15975";

	public const string TREASURECHEST_SILVER_STRANGEMAGIC_SC_1 = "15976";

	public const string TREASURECHEST_SILVER_STRANGEMAGIC_SC_2 = "15977";

	public const string TREASURECHEST_SILVER_STRANGEMAGIC_SC_3 = "15978";

	public const string TREASURECHEST_GOLD_STRANGEMAGIC_GC_1 = "15979";

	public const string TREASURECHEST_GOLD_STRANGEMAGIC_GC_2 = "15980";

	public const string QUESTREWARD_RIVEROFWOES = "16950";

	public const string TREASURECHEST_BRONZE_RIVEROFWOES_BC_1 = "16951";

	public const string TREASURECHEST_BRONZE_RIVEROFWOES_BC_2 = "16952";

	public const string TREASURECHEST_BRONZE_RIVEROFWOES_BC_3 = "16953";

	public const string TREASURECHEST_BRONZE_RIVEROFWOES_BC_4 = "16954";

	public const string TREASURECHEST_BRONZE_RIVEROFWOES_BC_5 = "16955";

	public const string TREASURECHEST_SILVER_RIVEROFWOES_SC_1 = "16956";

	public const string TREASURECHEST_SILVER_RIVEROFWOES_SC_2 = "16957";

	public const string TREASURECHEST_SILVER_RIVEROFWOES_SC_3 = "16958";

	public const string TREASURECHEST_GOLD_RIVEROFWOES_GC_1 = "16959";

	public const string TREASURECHEST_GOLD_RIVEROFWOES_GC_2 = "16960";

	public const string QUESTREWARD_YELLOPAINT = "17072";

	public const string TREASURECHEST_BRONZE_YELLOPAINT_BC_1 = "17073";

	public const string TREASURECHEST_BRONZE_YELLOPAINT_BC_2 = "17074";

	public const string TREASURECHEST_BRONZE_YELLOPAINT_BC_3 = "17075";

	public const string TREASURECHEST_BRONZE_YELLOPAINT_BC_4 = "17076";

	public const string TREASURECHEST_BRONZE_YELLOPAINT_BC_5 = "17077";

	public const string TREASURECHEST_SILVER_YELLOPAINT_SC_1 = "17078";

	public const string TREASURECHEST_SILVER_YELLOPAINT_SC_2 = "17079";

	public const string TREASURECHEST_SILVER_YELLOPAINT_SC_3 = "17080";

	public const string TREASURECHEST_GOLD_YELLOPAINT_GC_1 = "17081";

	public const string TREASURECHEST_GOLD_YELLOPAINT_GC_2 = "17082";

	public const string QUESTREWARD_ANCIENTHISTORY = "17122";

	public const string TREASURECHEST_BRONZE_ANCIENTHISTORY_BC_1 = "17123";

	public const string TREASURECHEST_BRONZE_ANCIENTHISTORY_BC_2 = "17124";

	public const string TREASURECHEST_BRONZE_ANCIENTHISTORY_BC_3 = "17125";

	public const string TREASURECHEST_BRONZE_ANCIENTHISTORY_BC_4 = "17126";

	public const string TREASURECHEST_BRONZE_ANCIENTHISTORY_BC_5 = "17127";

	public const string TREASURECHEST_SILVER_ANCIENTHISTORY_SC_1 = "17128";

	public const string TREASURECHEST_SILVER_ANCIENTHISTORY_SC_2 = "17129";

	public const string TREASURECHEST_SILVER_ANCIENTHISTORY_SC_3 = "17130";

	public const string TREASURECHEST_GOLD_ANCIENTHISTORY_GC_1 = "17131";

	public const string TREASURECHEST_GOLD_ANCIENTHISTORY_GC_2 = "17132";

	public const string QUESTREWARD_DAILYQUESTS_FEEDTHEBLOODTREETEMP = "17155";

	public const string QUESTREWARD_DAILYQUESTS_REWARDS_LOOTTABLETEMP = "17156";

	public const string QUESTREWARD_GARDENOFEVIL = "17282";

	public const string QUESTREWARD_COSMETICCON = "17294";

	public const string TREASURECHEST_BRONZE_COSMETICCON_BC_1 = "17295";

	public const string TREASURECHEST_BRONZE_COSMETICCON_BC_2 = "17296";

	public const string TREASURECHEST_BRONZE_COSMETICCON_BC_3 = "17297";

	public const string TREASURECHEST_BRONZE_COSMETICCON_BC_4 = "17298";

	public const string TREASURECHEST_BRONZE_COSMETICCON_BC_5 = "17299";

	public const string TREASURECHEST_SILVER_COSMETICCON_SC_1 = "17300";

	public const string TREASURECHEST_SILVER_COSMETICCON_SC_2 = "17301";

	public const string TREASURECHEST_SILVER_GARDENOFEVIL_SC_3 = "17302";

	public const string TREASURECHEST_GOLD_COSMETICCON_GC_1 = "17303";

	public const string TREASURECHEST_GOLD_COSMETICCON_GC_2 = "17304";

	public const string TREASURECHEST_BRONZE_GARDENOFEVIL_BC_1 = "17305";

	public const string TREASURECHEST_BRONZE_GARDENOFEVIL_BC_2 = "17306";

	public const string TREASURECHEST_BRONZE_GARDENOFEVIL_BC_3 = "17307";

	public const string TREASURECHEST_BRONZE_GARDENOFEVIL_BC_4 = "17308";

	public const string TREASURECHEST_BRONZE_GARDENOFEVIL_BC_5 = "17309";

	public const string TREASURECHEST_SILVER_GARDENOFEVIL_SC_1 = "17310";

	public const string TREASURECHEST_SILVER_GARDENOFEVIL_SC_2 = "17311";

	public const string TREASURECHEST_SILVER_COSMETICCON_SC_3 = "17312";

	public const string TREASURECHEST_GOLD_GARDENOFEVIL_GC_1 = "17313";

	public const string TREASURECHEST_GOLD_GARDENOFEVIL_GC_2 = "17314";

	public const string QUESTREWARD_TREEHOUSEDISASTER = "17386";

	public const string TREASURECHEST_BRONZE_TREEHOUSEDISASTER_BC_1 = "17387";

	public const string TREASURECHEST_BRONZE_TREEHOUSEDISASTER_BC_2 = "17388";

	public const string TREASURECHEST_BRONZE_TREEHOUSEDISASTER_BC_3 = "17389";

	public const string TREASURECHEST_BRONZE_TREEHOUSEDISASTER_BC_4 = "17390";

	public const string TREASURECHEST_BRONZE_TREEHOUSEDISASTER_BC_5 = "17391";

	public const string TREASURECHEST_SILVER_TREEHOUSEDISASTER_SC_1 = "17392";

	public const string TREASURECHEST_SILVER_TREEHOUSEDISASTER_SC_2 = "17393";

	public const string TREASURECHEST_SILVER_TREEHOUSEDISASTER_SC_3 = "17394";

	public const string TREASURECHEST_GOLD_TREEHOUSEDISASTER_GC_1 = "17395";

	public const string TREASURECHEST_GOLD_TREEHOUSEDISASTER_GC_2 = "17396";

	public const string QUESTREWARD_SNOWSHACK = "17619";

	public const string TREASURECHEST_GOLD_SNOWSHACK_GC_2 = "17620";

	public const string TREASURECHEST_GOLD_SNOWSHACK_GC_1 = "17621";

	public const string TREASURECHEST_SILVER_SNOWSHACK_SC_3 = "17622";

	public const string TREASURECHEST_SILVER_SNOWSHACK_SC_2 = "17623";

	public const string TREASURECHEST_SILVER_SNOWSHACK_SC_1 = "17624";

	public const string TREASURECHEST_BRONZE_SNOWSHACK_BC_5 = "17625";

	public const string TREASURECHEST_BRONZE_SNOWSHACK_BC_4 = "17626";

	public const string TREASURECHEST_BRONZE_SNOWSHACK_BC_3 = "17627";

	public const string TREASURECHEST_BRONZE_SNOWSHACK_BC_2 = "17628";

	public const string TREASURECHEST_BRONZE_SNOWSHACK_BC_1 = "17629";

	public const string QUESTREWARD_GHOSTDOG = "18437";

	public const string TREASURECHEST_GOLD_GHOSTDOG_GC_2 = "18438";

	public const string TREASURECHEST_GOLD_GHOSTDOG_GC_1 = "18439";

	public const string TREASURECHEST_SILVER_GHOSTDOG_SC_3 = "18440";

	public const string TREASURECHEST_SILVER_GHOSTDOG_SC_2 = "18441";

	public const string TREASURECHEST_SILVER_GHOSTDOG_SC_1 = "18442";

	public const string TREASURECHEST_BRONZE_GHOSTDOG_BC_5 = "18443";

	public const string TREASURECHEST_BRONZE_GHOSTDOG_BC_4 = "18444";

	public const string TREASURECHEST_BRONZE_GHOSTDOG_BC_3 = "18445";

	public const string TREASURECHEST_BRONZE_GHOSTDOG_BC_2 = "18446";

	public const string TREASURECHEST_BRONZE_GHOSTDOG_BC_1 = "18447";

	public const string TREASURECHEST_SILVER_BABYBOOMERS_SC_3 = "18990";

	public const string TREASURECHEST_SILVER_BABYBOOMERS_SC_2 = "18991";

	public const string TREASURECHEST_SILVER_BABYBOOMERS_SC_1 = "18992";

	public const string TREASURECHEST_GOLD_BABYBOOMERS_GC_2 = "18993";

	public const string TREASURECHEST_GOLD_BABYBOOMERS_GC_1 = "18994";

	public const string TREASURECHEST_BRONZE_BABYBOOMERS_BC_5 = "18995";

	public const string TREASURECHEST_BRONZE_BABYBOOMERS_BC_4 = "18996";

	public const string TREASURECHEST_BRONZE_BABYBOOMERS_BC_3 = "18997";

	public const string TREASURECHEST_BRONZE_BABYBOOMERS_BC_2 = "18998";

	public const string TREASURECHEST_BRONZE_BABYBOOMERS_BC_1 = "18999";

	public const string QUESTREWARD_BABYBOOMERS = "19000";

	public const string EMERGENTGAMEPLAY_ROCKFLIP_BABYBOOMERS = "19001";

	public const string QUESTREWARD_LONELYSNOWBOLD = "19004";

	public const string TREASURECHEST_BRONZE_LONELYSNOWBOLD_BC_1 = "19005";

	public const string TREASURECHEST_BRONZE_LONELYSNOWBOLD_BC_2 = "19006";

	public const string TREASURECHEST_BRONZE_LONELYSNOWBOLD_BC_3 = "19007";

	public const string TREASURECHEST_BRONZE_LONELYSNOWBOLD_BC_4 = "19008";

	public const string TREASURECHEST_BRONZE_LONELYSNOWBOLD_BC_5 = "19009";

	public const string TREASURECHEST_SILVER_LONELYSNOWBOLD_SC_1 = "19010";

	public const string TREASURECHEST_SILVER_LONELYSNOWBOLD_SC_2 = "19011";

	public const string TREASURECHEST_SILVER_LONELYSNOWBOLD_SC_3 = "19012";

	public const string TREASURECHEST_GOLD_LONELYSNOWBOLD_GC_1 = "19013";

	public const string TREASURECHEST_GOLD_LONELYSNOWBOLD_GC_2 = "19014";

	public const string QUESTREWARD_TWIGGLECOUNTDOWN = "19069";

	public const string TREASURECHEST_BRONZE_TWIGGLECOUNTDOWN_BC_1 = "19070";

	public const string TREASURECHEST_BRONZE_TWIGGLECOUNTDOWN_BC_2 = "19071";

	public const string TREASURECHEST_BRONZE_TWIGGLECOUNTDOWN_BC_3 = "19072";

	public const string TREASURECHEST_BRONZE_TWIGGLECOUNTDOWN_BC_4 = "19073";

	public const string TREASURECHEST_BRONZE_TWIGGLECOUNTDOWN_BC_5 = "19074";

	public const string TREASURECHEST_SILVER_TWIGGLECOUNTDOWN_SC_1 = "19075";

	public const string TREASURECHEST_SILVER_TWIGGLECOUNTDOWN_SC_2 = "19076";

	public const string TREASURECHEST_SILVER_TWIGGLECOUNTDOWN_SC_3 = "19077";

	public const string TREASURECHEST_GOLD_TWIGGLECOUNTDOWN_GC_1 = "19078";

	public const string TREASURECHEST_GOLD_TWIGGLECOUNTDOWN_GC_2 = "19079";

	public const string QUESTREWARD_SPRINKLEBURRITO = "19114";

	public const string TREASURECHEST_BRONZE_SPRINKLEBURRITO_BC_1 = "19115";

	public const string TREASURECHEST_BRONZE_SPRINKLEBURRITO_BC_2 = "19116";

	public const string TREASURECHEST_BRONZE_SPRINKLEBURRITO_BC_3 = "19117";

	public const string TREASURECHEST_BRONZE_SPRINKLEBURRITO_BC_4 = "19118";

	public const string TREASURECHEST_BRONZE_SPRINKLEBURRITO_BC_5 = "19119";

	public const string TREASURECHEST_GOLD_SPRINKLEBURRITO_GC_1 = "19120";

	public const string TREASURECHEST_GOLD_SPRINKLEBURRITO_GC_2 = "19121";

	public const string TREASURECHEST_SILVER_SPRINKLEBURRITO_SC_1 = "19122";

	public const string TREASURECHEST_SILVER_SPRINKLEBURRITO_SC_2 = "19123";

	public const string TREASURECHEST_SILVER_SPRINKLEBURRITO_SC_3 = "19124";

	public const string QUESTREWARD_FOLLOWFOOTSTEPS = "19146";

	public const string TREASURECHEST_BRONZE_FOLLOWFOOTSTEPS_BC_1 = "19147";

	public const string TREASURECHEST_BRONZE_FOLLOWFOOTSTEPS_BC_2 = "19148";

	public const string TREASURECHEST_BRONZE_FOLLOWFOOTSTEPS_BC_3 = "19149";

	public const string TREASURECHEST_BRONZE_FOLLOWFOOTSTEPS_BC_4 = "19150";

	public const string TREASURECHEST_BRONZE_FOLLOWFOOTSTEPS_BC_5 = "19151";

	public const string TREASURECHEST_SILVER_FOLLOWFOOTSTEPS_SC_1 = "19152";

	public const string TREASURECHEST_SILVER_FOLLOWFOOTSTEPS_SC_2 = "19153";

	public const string TREASURECHEST_SILVER_FOLLOWFOOTSTEPS_SC_3 = "19154";

	public const string TREASURECHEST_GOLD_FOLLOWFOOTSTEPS_GC_1 = "19155";

	public const string TREASURECHEST_GOLD_FOLLOWFOOTSTEPS_GC_2 = "19156";

	public const string TREASURECHEST_SILVER_PROTECTORSASSEMBLE_SC_3 = "19171";

	public const string TREASURECHEST_SILVER_PROTECTORSASSEMBLE_SC_2 = "19172";

	public const string TREASURECHEST_SILVER_PROTECTORSASSEMBLE_SC_1 = "19173";

	public const string TREASURECHEST_GOLD_PROTECTORSASSEMBLE_GC_2 = "19174";

	public const string TREASURECHEST_GOLD_PROTECTORSASSEMBLE_GC_1 = "19175";

	public const string TREASURECHEST_BRONZE_PROTECTORSASSEMBLE_BC_5 = "19176";

	public const string TREASURECHEST_BRONZE_PROTECTORSASSEMBLE_BC_4 = "19177";

	public const string TREASURECHEST_BRONZE_PROTECTORSASSEMBLE_BC_3 = "19178";

	public const string TREASURECHEST_BRONZE_PROTECTORSASSEMBLE_BC_2 = "19179";

	public const string TREASURECHEST_BRONZE_PROTECTORSASSEMBLE_BC_1 = "19180";

	public const string QUESTREWARD_PROTECTORSASSEMBLE = "19181";

	public const string QUESTREWARD_WELLWISHES = "19217";

	public const string TREASURECHEST_BRONZE_WELLWISHES_BC_1 = "19218";

	public const string TREASURECHEST_BRONZE_WELLWISHES_BC_2 = "19219";

	public const string TREASURECHEST_BRONZE_WELLWISHES_BC_3 = "19220";

	public const string TREASURECHEST_BRONZE_WELLWISHES_BC_4 = "19221";

	public const string TREASURECHEST_BRONZE_WELLWISHES_BC_5 = "19222";

	public const string TREASURECHEST_SILVER_WELLWISHES_SC_1 = "19223";

	public const string TREASURECHEST_SILVER_WELLWISHES_SC_2 = "19224";

	public const string TREASURECHEST_SILVER_WELLWISHES_SC_3 = "19225";

	public const string TREASURECHEST_GOLD_WELLWISHES_GC_1 = "19226";

	public const string TREASURECHEST_GOLD_WELLWISHES_GC_2 = "19227";

	public const string QUESTREWARD_CHASINGAWAYTHEBLUES = "19234";

	public const string TREASURECHEST_BRONZE_CHASINGAWAYTHEBLUES_BC_1 = "19235";

	public const string TREASURECHEST_BRONZE_CHASINGAWAYTHEBLUES_BC_2 = "19236";

	public const string TREASURECHEST_BRONZE_CHASINGAWAYTHEBLUES_BC_3 = "19237";

	public const string TREASURECHEST_BRONZE_CHASINGAWAYTHEBLUES_BC_4 = "19238";

	public const string TREASURECHEST_BRONZE_CHASINGAWAYTHEBLUES_BC_5 = "19239";

	public const string TREASURECHEST_GOLD_CHASINGAWAYTHEBLUES_GC_1 = "19240";

	public const string TREASURECHEST_GOLD_CHASINGAWAYTHEBLUES_GC_2 = "19241";

	public const string TREASURECHEST_SILVER_CHASINGAWAYTHEBLUES_SC_1 = "19242";

	public const string TREASURECHEST_SILVER_CHASINGAWAYTHEBLUES_SC_2 = "19243";

	public const string TREASURECHEST_SILVER_CHASINGAWAYTHEBLUES_SC_3 = "19244";

	public const string QUESTREWARD_PLANTINGSAPLINGS = "19264";

	public const string TREASURECHEST_BRONZE_PLANTINGSAPLINGS_BC_1 = "19265";

	public const string TREASURECHEST_BRONZE_PLANTINGSAPLINGS_BC_2 = "19266";

	public const string TREASURECHEST_BRONZE_PLANTINGSAPLINGS_BC_3 = "19267";

	public const string TREASURECHEST_BRONZE_PLANTINGSAPLINGS_BC_4 = "19268";

	public const string TREASURECHEST_BRONZE_PLANTINGSAPLINGS_BC_5 = "19269";

	public const string TREASURECHEST_GOLD_PLANTINGSAPLINGS_GC_1 = "19270";

	public const string TREASURECHEST_GOLD_PLANTINGSAPLINGS_GC_2 = "19271";

	public const string TREASURECHEST_SILVER_PLANTINGSAPLINGS_SC_1 = "19272";

	public const string TREASURECHEST_SILVER_PLANTINGSAPLINGS_SC_2 = "19273";

	public const string TREASURECHEST_SILVER_PLANTINGSAPLINGS_SC_3 = "19274";

	public const string QUESTREWARD_BESTSLEDS = "20569";

	public const string QUESTREWARD_SEASONALTEA = "20570";

	public const string TREASURECHEST_BRONZE_SEASONALTEA_BC_1 = "20571";

	public const string TREASURECHEST_BRONZE_SEASONALTEA_BC_2 = "20572";

	public const string TREASURECHEST_BRONZE_SEASONALTEA_BC_3 = "20573";

	public const string TREASURECHEST_BRONZE_SEASONALTEA_BC_4 = "20574";

	public const string TREASURECHEST_BRONZE_SEASONALTEA_BC_5 = "20575";

	public const string TREASURECHEST_SILVER_SEASONALTEA_SC_1 = "20576";

	public const string TREASURECHEST_SILVER_SEASONALTEA_SC_2 = "20577";

	public const string TREASURECHEST_SILVER_SEASONALTEA_SC_3 = "20578";

	public const string TREASURECHEST_GOLD_SEASONALTEA_GC_1 = "20579";

	public const string TREASURECHEST_GOLD_SEASONALTEA_GC_2 = "20580";

	public const string TREASURECHEST_BRONZE_BESTSLEDS_BC_1 = "20581";

	public const string TREASURECHEST_BRONZE_BESTSLEDS_BC_2 = "20582";

	public const string TREASURECHEST_BRONZE_BESTSLEDS_BC_3 = "20583";

	public const string TREASURECHEST_BRONZE_BESTSLEDS_BC_4 = "20584";

	public const string TREASURECHEST_BRONZE_BESTSLEDS_BC_5 = "20585";

	public const string TREASURECHEST_SILVER_BESTSLEDS_SC_1 = "20586";

	public const string TREASURECHEST_SILVER_BESTSLEDS_SC_2 = "20587";

	public const string TREASURECHEST_SILVER_BESTSLEDS_SC_3 = "20588";

	public const string TREASURECHEST_GOLD_BESTSLEDS_GC_1 = "20589";

	public const string TREASURECHEST_GOLD_BESTSLEDS_GC_2 = "20590";

	public const string QUESTREWARD_UNBOUNDSOULS = "20788";

	public const string TREASURECHEST_BRONZE_UNBOUNDSOULS_BC_1 = "20789";

	public const string TREASURECHEST_BRONZE_UNBOUNDSOULS_BC_2 = "20790";

	public const string TREASURECHEST_BRONZE_UNBOUNDSOULS_BC_3 = "20791";

	public const string TREASURECHEST_BRONZE_UNBOUNDSOULS_BC_4 = "20792";

	public const string TREASURECHEST_BRONZE_UNBOUNDSOULS_BC_5 = "20793";

	public const string TREASURECHEST_SILVER_UNBOUNDSOULS_SC_1 = "20794";

	public const string TREASURECHEST_SILVER_UNBOUNDSOULS_SC_2 = "20795";

	public const string TREASURECHEST_SILVER_UNBOUNDSOULS_SC_3 = "20796";

	public const string TREASURECHEST_GOLD_UNBOUNDSOULS_GC_1 = "20797";

	public const string TREASURECHEST_GOLD_UNBOUNDSOULS_GC_2 = "20798";

	public const string QUESTREWARD_BOKTOBERFEST = "20814";

	public const string TREASURECHEST_BRONZE_BOKTOBERFEST_BC_1 = "20815";

	public const string TREASURECHEST_BRONZE_BOKTOBERFEST_BC_2 = "20816";

	public const string TREASURECHEST_BRONZE_BOKTOBERFEST_BC_3 = "20817";

	public const string TREASURECHEST_BRONZE_BOKTOBERFEST_BC_4 = "20818";

	public const string TREASURECHEST_BRONZE_BOKTOBERFEST_BC_5 = "20819";

	public const string TREASURECHEST_SILVER_BOKTOBERFEST_SC_1 = "20820";

	public const string TREASURECHEST_SILVER_BOKTOBERFEST_SC_2 = "20821";

	public const string TREASURECHEST_SILVER_BOKTOBERFEST_SC_3 = "20822";

	public const string TREASURECHEST_GOLD_BOKTOBERFEST_GC_1 = "20823";

	public const string TREASURECHEST_GOLD_BOKTOBERFEST_GC_2 = "20824";

	public const string QUESTREWARD_NOVELROMANCE = "20845";

	public const string TREASURECHEST_BRONZE_NOVELROMANCE_BC_1 = "20846";

	public const string TREASURECHEST_BRONZE_NOVELROMANCE_BC_2 = "20847";

	public const string TREASURECHEST_BRONZE_NOVELROMANCE_BC_3 = "20848";

	public const string TREASURECHEST_BRONZE_NOVELROMANCE_BC_4 = "20849";

	public const string TREASURECHEST_BRONZE_NOVELROMANCE_BC_5 = "20850";

	public const string TREASURECHEST_SILVER_NOVELROMANCE_SC_1 = "20851";

	public const string TREASURECHEST_SILVER_NOVELROMANCE_SC_2 = "20852";

	public const string TREASURECHEST_SILVER_NOVELROMANCE_SC_3 = "20853";

	public const string TREASURECHEST_GOLD_NOVELROMANCE_GC_1 = "20854";

	public const string TREASURECHEST_GOLD_NOVELROMANCE_GC_2 = "20855";

	public const string QUESTREWARD_GUARDIANANGEL = "20886";

	public const string TREASURECHEST_BRONZE_GUARDIANANGEL_BC_1 = "20887";

	public const string TREASURECHEST_BRONZE_GUARDIANANGEL_BC_2 = "20888";

	public const string TREASURECHEST_BRONZE_GUARDIANANGEL_BC_3 = "20889";

	public const string TREASURECHEST_BRONZE_GUARDIANANGEL_BC_4 = "20890";

	public const string TREASURECHEST_BRONZE_GUARDIANANGEL_BC_5 = "20891";

	public const string TREASURECHEST_GOLD_GUARDIANANGEL_GC_1 = "20892";

	public const string TREASURECHEST_GOLD_GUARDIANANGEL_GC_2 = "20893";

	public const string TREASURECHEST_SILVER_GUARDIANANGEL_SC_1 = "20894";

	public const string TREASURECHEST_SILVER_GUARDIANANGEL_SC_2 = "20895";

	public const string TREASURECHEST_SILVER_GUARDIANANGEL_SC_3 = "20896";

	public const string QUESTREWARD_HOCUSPOCUS = "20897";

	public const string TREASURECHEST_BRONZE_HOCUSPOCUS_BC_1 = "20898";

	public const string TREASURECHEST_BRONZE_HOCUSPOCUS_BC_2 = "20899";

	public const string TREASURECHEST_BRONZE_HOCUSPOCUS_BC_3 = "20900";

	public const string TREASURECHEST_BRONZE_HOCUSPOCUS_BC_4 = "20901";

	public const string TREASURECHEST_BRONZE_HOCUSPOCUS_BC_5 = "20902";

	public const string TREASURECHEST_GOLD_HOCUSPOCUS_GC_1 = "20903";

	public const string TREASURECHEST_GOLD_HOCUSPOCUS_GC_2 = "20904";

	public const string TREASURECHEST_SILVER_HOCUSPOCUS_SC_1 = "20905";

	public const string TREASURECHEST_SILVER_HOCUSPOCUS_SC_2 = "20906";

	public const string TREASURECHEST_SILVER_HOCUSPOCUS_SC_3 = "20907";

	public const string QUESTREWARD_POOFYPOACHERS = "21033";

	public const string TREASURECHEST_BRONZE_POOFYPOACHERS_BC_1 = "21034";

	public const string TREASURECHEST_BRONZE_POOFYPOACHERS_BC_2 = "21035";

	public const string TREASURECHEST_BRONZE_POOFYPOACHERS_BC_3 = "21036";

	public const string TREASURECHEST_BRONZE_POOFYPOACHERS_BC_4 = "21037";

	public const string TREASURECHEST_BRONZE_POOFYPOACHERS_BC_5 = "21038";

	public const string TREASURECHEST_SILVER_POOFYPOACHERS_SC_1 = "21039";

	public const string TREASURECHEST_SILVER_POOFYPOACHERS_SC_2 = "21040";

	public const string TREASURECHEST_SILVER_POOFYPOACHERS_SC_3 = "21041";

	public const string TREASURECHEST_GOLD_POOFYPOACHERS_GC_1 = "21042";

	public const string TREASURECHEST_GOLD_POOFYPOACHERS_GC_2 = "21043";

	public const string TREASURECHEST_SILVER_TOBBOGANRUN_SC_3 = "21095";

	public const string TREASURECHEST_SILVER_TOBBOGANRUN_SC_2 = "21096";

	public const string TREASURECHEST_SILVER_TOBBOGANRUN_SC_1 = "21097";

	public const string TREASURECHEST_GOLD_TOBBOGANRUN_GC_2 = "21098";

	public const string TREASURECHEST_GOLD_TOBBOGANRUN_GC_1 = "21099";

	public const string TREASURECHEST_BRONZE_TOBBOGANRUN_BC_5 = "21100";

	public const string TREASURECHEST_BRONZE_TOBBOGANRUN_BC_4 = "21101";

	public const string TREASURECHEST_BRONZE_TOBBOGANRUN_BC_3 = "21102";

	public const string TREASURECHEST_BRONZE_TOBBOGANRUN_BC_2 = "21103";

	public const string TREASURECHEST_BRONZE_TOBBOGANRUN_BC_1 = "21104";

	public const string QUESTREWARD_TOBBOGANRUN = "21105";

	public const string QUESTREWARD_POOFYPOACHERSBONUS = "21118";

	public const string TREASURECHEST_BRONZE_TEST5 = "23803";

	public const string TREASURECHEST_BRONZE_TEST4 = "23804";

	public const string TREASURECHEST_BRONZE_TEST3 = "23805";

	public const string TREASURECHEST_BRONZE_TEST2 = "23806";

	public const string TREASURECHEST_BRONZE_TEST1 = "23807";

	public const string TREASURECHEST_GOLD_BACKSCRATCHERS_GC_3 = "23838";

	public const string TREASURECHEST_GOLD_SUCKEREDIN_GC_3 = "23839";

	public const string QUESTREWARD_CITYFERATUTORIAL = "25525";

	public const string TREASURECHEST_GOLD_MARCH2021_TUNDRAGC_1 = "26819";

	public const string TREASURECHEST_GOLD_MARCH2021_TUNDRAGC_2 = "26820";

	public const string TREASURECHEST_GOLD_MARCH2021_TUNDRAGC_3 = "26821";

	public const string TREASURECHEST_GOLD_MARCH2021_FORESTGC_1 = "26822";

	public const string TREASURECHEST_GOLD_MARCH2021_FORESTGC_2 = "26823";

	public const string TREASURECHEST_GOLD_MARCH2021_FORESTGC_3 = "26824";

	public const string TREASURECHEST_GOLD_MARCH2021_SWAMPGC_1 = "26825";

	public const string TREASURECHEST_GOLD_MARCH2021_SWAMPGC_2 = "26826";

	public const string TREASURECHEST_GOLD_MARCH2021_SWAMPGC_3 = "26827";

	public const string TREASURECHEST_SILVER_MARCH2021_TUNDRASC_1 = "26828";

	public const string TREASURECHEST_SILVER_MARCH2021_TUNDRASC_2 = "26829";

	public const string TREASURECHEST_SILVER_MARCH2021_TUNDRASC_3 = "26830";

	public const string TREASURECHEST_SILVER_MARCH2021_TUNDRASC_4 = "26831";

	public const string TREASURECHEST_SILVER_MARCH2021_TUNDRASC_5 = "26832";

	public const string TREASURECHEST_SILVER_MARCH2021_TUNDRASC_6 = "26833";

	public const string TREASURECHEST_SILVER_MARCH2021_TUNDRASC_7 = "26834";

	public const string TREASURECHEST_SILVER_MARCH2021_FORESTSC_1 = "26835";

	public const string TREASURECHEST_SILVER_MARCH2021_SWAMPSC_1 = "26836";

	public const string TREASURECHEST_SILVER_MARCH2021_FORESTSC_2 = "26837";

	public const string TREASURECHEST_SILVER_MARCH2021_SWAMPSC_2 = "26838";

	public const string TREASURECHEST_SILVER_MARCH2021_FORESTSC_3 = "26839";

	public const string TREASURECHEST_SILVER_MARCH2021_SWAMPSC_3 = "26840";

	public const string TREASURECHEST_SILVER_MARCH2021_FORESTSC_4 = "26841";

	public const string TREASURECHEST_SILVER_MARCH2021_SWAMPSC_4 = "26842";

	public const string TREASURECHEST_SILVER_MARCH2021_FORESTSC_5 = "26843";

	public const string TREASURECHEST_SILVER_MARCH2021_SWAMPSC_5 = "26844";

	public const string TREASURECHEST_SILVER_MARCH2021_FORESTSC_6 = "26845";

	public const string TREASURECHEST_SILVER_MARCH2021_SWAMPSC_6 = "26846";

	public const string TREASURECHEST_SILVER_MARCH2021_FORESTSC_7 = "26847";

	public const string TREASURECHEST_SILVER_MARCH2021_SWAMPSC_7 = "26848";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_1 = "26849";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_2 = "26850";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_3 = "26851";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_4 = "26852";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_5 = "26853";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_6 = "26854";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_7 = "26855";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_8 = "26856";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_9 = "26857";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_10 = "26858";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_11 = "26859";

	public const string TREASURECHEST_BRONZE_MARCH2021_TUNDRABC_12 = "26860";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_1 = "26861";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_10 = "26862";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_11 = "26863";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_12 = "26864";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_2 = "26865";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_3 = "26866";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_4 = "26867";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_5 = "26868";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_6 = "26869";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_7 = "26870";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_8 = "26871";

	public const string TREASURECHEST_BRONZE_MARCH2021_FORESTBC_9 = "26872";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_1 = "26873";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_10 = "26874";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_11 = "26875";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_12 = "26876";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_2 = "26877";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_3 = "26878";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_4 = "26879";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_5 = "26880";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_6 = "26881";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_7 = "26882";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_8 = "26883";

	public const string TREASURECHEST_BRONZE_MARCH2021_SWAMPBC_9 = "26884";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_1 = "27868";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_10 = "27869";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_11 = "27870";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_12 = "27871";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_2 = "27872";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_3 = "27873";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_4 = "27874";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_5 = "27875";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_6 = "27876";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_7 = "27877";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_8 = "27878";

	public const string TREASURECHEST_BRONZE_APRIL2021_FORESTBC_9 = "27879";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_1 = "27880";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_10 = "27881";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_11 = "27882";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_12 = "27883";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_2 = "27884";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_3 = "27885";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_4 = "27886";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_5 = "27887";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_6 = "27888";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_7 = "27889";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_8 = "27890";

	public const string TREASURECHEST_BRONZE_APRIL2021_SWAMPBC_9 = "27891";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_1 = "27892";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_10 = "27893";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_11 = "27894";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_12 = "27895";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_2 = "27896";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_3 = "27897";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_4 = "27898";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_5 = "27899";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_6 = "27900";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_7 = "27901";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_8 = "27902";

	public const string TREASURECHEST_BRONZE_APRIL2021_TUNDRABC_9 = "27903";

	public const string TREASURECHEST_GOLD_APRIL2021_FORESTGC_1 = "27904";

	public const string TREASURECHEST_GOLD_APRIL2021_FORESTGC_2 = "27905";

	public const string TREASURECHEST_GOLD_APRIL2021_FORESTGC_3 = "27906";

	public const string TREASURECHEST_GOLD_APRIL2021_SWAMPGC_1 = "27907";

	public const string TREASURECHEST_GOLD_APRIL2021_SWAMPGC_2 = "27908";

	public const string TREASURECHEST_GOLD_APRIL2021_SWAMPGC_3 = "27909";

	public const string TREASURECHEST_GOLD_APRIL2021_TUNDRAGC_1 = "27910";

	public const string TREASURECHEST_GOLD_APRIL2021_TUNDRAGC_2 = "27911";

	public const string TREASURECHEST_GOLD_APRIL2021_TUNDRAGC_3 = "27912";

	public const string TREASURECHEST_SILVER_APRIL2021_FORESTSC_1 = "27913";

	public const string TREASURECHEST_SILVER_APRIL2021_FORESTSC_2 = "27914";

	public const string TREASURECHEST_SILVER_APRIL2021_FORESTSC_3 = "27915";

	public const string TREASURECHEST_SILVER_APRIL2021_FORESTSC_4 = "27916";

	public const string TREASURECHEST_SILVER_APRIL2021_FORESTSC_5 = "27917";

	public const string TREASURECHEST_SILVER_APRIL2021_FORESTSC_6 = "27918";

	public const string TREASURECHEST_SILVER_APRIL2021_FORESTSC_7 = "27919";

	public const string TREASURECHEST_SILVER_APRIL2021_SWAMPSC_1 = "27920";

	public const string TREASURECHEST_SILVER_APRIL2021_SWAMPSC_2 = "27921";

	public const string TREASURECHEST_SILVER_APRIL2021_SWAMPSC_3 = "27922";

	public const string TREASURECHEST_SILVER_APRIL2021_SWAMPSC_4 = "27923";

	public const string TREASURECHEST_SILVER_APRIL2021_SWAMPSC_5 = "27924";

	public const string TREASURECHEST_SILVER_APRIL2021_SWAMPSC_6 = "27925";

	public const string TREASURECHEST_SILVER_APRIL2021_SWAMPSC_7 = "27926";

	public const string TREASURECHEST_SILVER_APRIL2021_TUNDRASC_1 = "27927";

	public const string TREASURECHEST_SILVER_APRIL2021_TUNDRASC_2 = "27928";

	public const string TREASURECHEST_SILVER_APRIL2021_TUNDRASC_3 = "27929";

	public const string TREASURECHEST_SILVER_APRIL2021_TUNDRASC_4 = "27930";

	public const string TREASURECHEST_SILVER_APRIL2021_TUNDRASC_5 = "27931";

	public const string TREASURECHEST_SILVER_APRIL2021_TUNDRASC_6 = "27932";

	public const string TREASURECHEST_SILVER_APRIL2021_TUNDRASC_7 = "27933";

	public const string PICKUP_SKYJELLYBLOOM = "28487";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_1 = "29252";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_10 = "29253";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_11 = "29254";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_12 = "29255";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_2 = "29256";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_3 = "29257";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_4 = "29258";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_5 = "29259";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_6 = "29260";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_7 = "29261";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_8 = "29262";

	public const string TREASURECHEST_BRONZE_MAY2021_FORESTBC_9 = "29263";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_1 = "29264";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_10 = "29265";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_11 = "29266";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_12 = "29267";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_2 = "29268";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_3 = "29269";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_4 = "29270";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_5 = "29271";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_6 = "29272";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_7 = "29273";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_8 = "29274";

	public const string TREASURECHEST_BRONZE_MAY2021_SWAMPBC_9 = "29275";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_1 = "29276";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_10 = "29277";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_11 = "29278";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_12 = "29279";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_2 = "29280";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_3 = "29281";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_4 = "29282";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_5 = "29283";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_6 = "29284";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_7 = "29285";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_8 = "29286";

	public const string TREASURECHEST_BRONZE_MAY2021_TUNDRABC_9 = "29287";

	public const string TREASURECHEST_GOLD_MAY2021_FORESTGC_1 = "29288";

	public const string TREASURECHEST_GOLD_MAY2021_FORESTGC_2 = "29289";

	public const string TREASURECHEST_GOLD_MAY2021_FORESTGC_3 = "29290";

	public const string TREASURECHEST_GOLD_MAY2021_SWAMPGC_1 = "29291";

	public const string TREASURECHEST_GOLD_MAY2021_SWAMPGC_2 = "29292";

	public const string TREASURECHEST_GOLD_MAY2021_SWAMPGC_3 = "29293";

	public const string TREASURECHEST_GOLD_MAY2021_TUNDRAGC_1 = "29294";

	public const string TREASURECHEST_GOLD_MAY2021_TUNDRAGC_2 = "29295";

	public const string TREASURECHEST_GOLD_MAY2021_TUNDRAGC_3 = "29296";

	public const string TREASURECHEST_SILVER_MAY2021_FORESTSC_1 = "29297";

	public const string TREASURECHEST_SILVER_MAY2021_FORESTSC_2 = "29298";

	public const string TREASURECHEST_SILVER_MAY2021_FORESTSC_3 = "29299";

	public const string TREASURECHEST_SILVER_MAY2021_FORESTSC_4 = "29300";

	public const string TREASURECHEST_SILVER_MAY2021_FORESTSC_5 = "29301";

	public const string TREASURECHEST_SILVER_MAY2021_FORESTSC_6 = "29302";

	public const string TREASURECHEST_SILVER_MAY2021_FORESTSC_7 = "29303";

	public const string TREASURECHEST_SILVER_MAY2021_SWAMPSC_1 = "29304";

	public const string TREASURECHEST_SILVER_MAY2021_SWAMPSC_2 = "29305";

	public const string TREASURECHEST_SILVER_MAY2021_SWAMPSC_3 = "29306";

	public const string TREASURECHEST_SILVER_MAY2021_SWAMPSC_4 = "29307";

	public const string TREASURECHEST_SILVER_MAY2021_SWAMPSC_5 = "29308";

	public const string TREASURECHEST_SILVER_MAY2021_SWAMPSC_6 = "29309";

	public const string TREASURECHEST_SILVER_MAY2021_SWAMPSC_7 = "29310";

	public const string TREASURECHEST_SILVER_MAY2021_TUNDRASC_1 = "29311";

	public const string TREASURECHEST_SILVER_MAY2021_TUNDRASC_2 = "29312";

	public const string TREASURECHEST_SILVER_MAY2021_TUNDRASC_3 = "29313";

	public const string TREASURECHEST_SILVER_MAY2021_TUNDRASC_4 = "29314";

	public const string TREASURECHEST_SILVER_MAY2021_TUNDRASC_5 = "29315";

	public const string TREASURECHEST_SILVER_MAY2021_TUNDRASC_6 = "29316";

	public const string TREASURECHEST_SILVER_MAY2021_TUNDRASC_7 = "29317";

	public const string TREASURECHEST_BLOODTUNDRA_BRONZE = "30583";

	public const string TREASURECHEST_BLOODTUNDRA_SILVER = "30584";

	public const string TREASURECHEST_BLOODTUNDRA_GOLD = "30585";

	public const string TREASURECHEST_FOREST_BRONZE = "30586";

	public const string TREASURECHEST_FOREST_SILVER = "30587";

	public const string TREASURECHEST_FOREST_GOLD = "30588";

	public const string TREASURECHEST_SWAMP_GOLD = "30589";

	public const string TREASURECHEST_SWAMP_SILVER = "30590";

	public const string TREASURECHEST_SWAMP_BRONZE = "30591";
}
