public class SanctuaryGreenhouseTemplate : SanctuaryFurnitureTemplate
{
	public SanctuaryGreenhouseDefComponent sanctuaryGreenhouseDefComponent;

	public SanctuaryGreenhouseExteriorGetModelDefComponent sanctuaryGreenhouseExteriorGetModelDefComponent;

	public SanctuaryGreenhouseInteriorGetModelDefComponent sanctuaryGreenhouseInteriorGetModelDefComponent;

	public SanctuaryGreenhouseExteriorDoorGetModelDefComponent sanctuaryGreenhouseExteriorDoorGetModelDefComponent;
}
