public class SocialExpanseGenericQuestCompletedMessage : Message
{
	public readonly SocialExpanseLinearGenericQuestsCompletionItemComponent socialExpanseQuestCompletionItemComponent;

	public SocialExpanseGenericQuestCompletedMessage(SocialExpanseLinearGenericQuestsCompletionItemComponent inSocialExpanseCompletionItemComponent)
	{
	}
}
