public class SocialExpanseChestUnlockedMessage : Message
{
	public readonly SocialExpanseGroupLinearObjectsProgressItemComponent socialExpanseProgressItemComponent;

	public SocialExpanseChestUnlockedMessage(SocialExpanseGroupLinearObjectsProgressItemComponent inSocialExpanseProgressItemComponent)
	{
	}
}
