namespace Server
{
	public enum XtCmd
	{
		[Cmd("utc")]
		TutorialComplete,
		[Cmd("utcD")]
		TutorialComplete_DEBUG,
		[Cmd("anf")]
		AnalyticsFeedback,
		[Cmd("ans")]
		AnalyticsSelfie,
		[Cmd("alg")]
		AvatarLookGet,
		[Cmd("aa")]
		AvatarAction,
		[Cmd("als")]
		AvatarLookSwitch,
		[Cmd("alz")]
		AvatarLookCustomize,
		[Cmd("$b")]
		ShopBuyItem,
		[Cmd("$bb")]
		ShopBuyBundle,
		[Cmd("$cx")]
		ShopCurrencyExchange,
		[Cmd("$l")]
		ShopList,
		[Cmd("$ui")]
		ShopUnlockItem,
		[Cmd("sj")]
		SanctuaryJoin,
		[Cmd("ssu")]
		SanctuaryStateUpdate,
		[Cmd("sus")]
		SanctuaryUpgradeStart,
		[Cmd("suc")]
		SanctuaryUpgradeComplete,
		[Cmd("sp")]
		SanctuaryPurchase,
		[Cmd("ssw")]
		SanctuarySwitch,
		[Cmd("sls")]
		SanctuaryLookSave,
		[Cmd("sll")]
		SanctuaryLookLoad,
		[Cmd("ua")]
		Announcement,
		[Cmd("up")]
		SystemPopup,
		[Cmd("ulc")]
		LoginComplete,
		[Cmd("dgm")]
		DirectGenericMessage,
		[Cmd("gtc")]
		GroupTeamCreate,
		[Cmd("gtj")]
		GroupTeamJoin,
		[Cmd("gtl")]
		GroupTeamLeave,
		[Cmd("gtuj")]
		GroupTeamUserJoined,
		[Cmd("gtul")]
		GroupTeamUserLeft,
		[Cmd("gta")]
		GroupTeamAnnounce,
		[Cmd("gtq")]
		GroupTeamQuest,
		[Cmd("gti")]
		GroupTeamInvite,
		[Cmd("gtia")]
		GroupTeamInviteAccept,
		[Cmd("gtir")]
		GroupTeamInviteReject,
		[Cmd("gr")]
		GiftRedeem,
		[Cmd("grm")]
		GiftRedeemMulti,
		[Cmd("gp")]
		GiftPush,
		[Cmd("ggD")]
		GiftGiveDEBUG,
		[Cmd("il")]
		ItemListResponse,
		[Cmd("ilm")]
		ItemListMoreResponse,
		[Cmd("iic")]
		ItemInspirationCombine,
		[Cmd("ilt")]
		ItemListOfTypeRequest,
		[Cmd("ilc")]
		ItemListWithComponentRequest,
		[Cmd("ilr")]
		ItemListRemovedResponse,
		[Cmd("ii")]
		ItemInfoRequest,
		[Cmd("ic")]
		ItemCraft,
		[Cmd("iu")]
		ItemUncraft,
		[Cmd("igD")]
		ItemAdd_DEBUG,
		[Cmd("igE")]
		ItemAdd_ENIGMA,
		[Cmd("iud")]
		ItemUseDye,
		[Cmd("rj")]
		RoomJoin,
		[Cmd("rjp")]
		RoomJoinPrevious,
		[Cmd("rjt")]
		RoomJoinTutorial,
		[Cmd("rfosu")]
		RelationshipFollowOnlineStatusUpdate,
		[Cmd("rfl")]
		RelationshipFollowingList,
		[Cmd("rfo")]
		RelationshipOnlineStatus,
		[Cmd("rfjtr")]
		RelationshipFollowerJumpToRoom,
		[Cmd("rffpu")]
		RelationshipFollowingFindPlayerUUID,
		[Cmd("wr")]
		WorldReady,
		[Cmd("ou")]
		WorldObjectUpdate,
		[Cmd("og")]
		WorldObjectGlide,
		[Cmd("oge")]
		WorldObjectGlideEnterExit,
		[Cmd("oi")]
		WorldObjectInfo,
		[Cmd("oial")]
		WorldObjectInfoAvatarLocal,
		[Cmd("oa")]
		WorldObjectAction,
		[Cmd("oas")]
		WorldObjectActionStart,
		[Cmd("oac")]
		WorldObjectActionCancel,
		[Cmd("oaf")]
		WorldObjectActionFinish,
		[Cmd("od")]
		WorldObjectDelete,
		[Cmd("ob")]
		WorldObjectBroadcast,
		[Cmd("oaskr")]
		WorldObjectAskResponse,
		[Cmd("ors")]
		WorldObjectRespawnSet,
		[Cmd("orr")]
		WorldObjectRespawnRequest,
		[Cmd("lc")]
		LobbyCreate,
		[Cmd("lj")]
		LobbyJoin,
		[Cmd("ll")]
		LobbyLeave,
		[Cmd("ls")]
		LobbyStart,
		[Cmd("qa")]
		QuestAdd,
		[Cmd("qo")]
		QuestOpen,
		[Cmd("qs")]
		QuestStart,
		[Cmd("qcmd")]
		QuestCommand,
		[Cmd("qat")]
		QuestActorTriggered,
		[Cmd("qcmdVT")]
		QuestCommandVT,
		[Cmd("qsgo")]
		QuestSetupGroupObjects,
		[Cmd("qsxqc")]
		QuestGenericLinearQuestComplete,
		[Cmd("qsxrqD")]
		QuestResetQuestsDEBUG,
		[Cmd("fcs")]
		SyncClock,
		[Cmd("_m_")]
		MultiMessage,
		[Cmd("ka")]
		KeepAlive,
		[Cmd("sv")]
		HydraServerIP,
		[Cmd("mj")]
		MinigameJoin,
		[Cmd("ms")]
		MinigameStart,
		[Cmd("mg")]
		MinigameCurrency,
		[Cmd("mpz")]
		MinigamePrize,
		[Cmd("mm")]
		MinigameMessage,
		[Cmd("mpg")]
		MinigameProgress,
		[Cmd("nhd")]
		NodeHopDrain,
		[Cmd("nhdg")]
		NodeHopDrainGo,
		[Cmd("zs")]
		UserVarSet,
		[Cmd("zsb")]
		UserVarSetBatch,
		[Cmd("ti")]
		TradeInitiate,
		[Cmd("tir")]
		TradeInitiateReject,
		[Cmd("tic")]
		TradeInitiateCancel,
		[Cmd("tia")]
		TradeInitiateAccept,
		[Cmd("tif")]
		TradeInitiateFail,
		[Cmd("tar")]
		TradeAddRemoveItem,
		[Cmd("tr")]
		TradeReady,
		[Cmd("tra")]
		TradeReadyAccept,
		[Cmd("trr")]
		TradeReadyReject,
		[Cmd("tx")]
		TradeExit,
		[Cmd("tl")]
		TradeList,
		[Cmd("tlu")]
		TradeListUpdate,
		[Cmd("fr")]
		FacilitatorReport,
		[Cmd("fsb")]
		FacilitatorSetBusy,
		[Cmd("fd")]
		FacilitatorDiscipline,
		[Cmd("fdd")]
		FacilitatorDebugDisconnect,
		[Cmd("fdc")]
		FacilitatorDisconnect,
		[Cmd("spcu")]
		SeasonPassChallengeUpdate,
		[Cmd("spcc")]
		SeasonPassChallengeComplete,
		[Cmd("sppt")]
		SeasonPassPurchaseTier,
		[Cmd("udv")]
		UserDataVersion,
		[Cmd("xpu")]
		XPUpdate,
		[Cmd("xpuD")]
		XPUpdateDEBUG,
		[Cmd("xpgD")]
		XPGiveDEBUG
	}
}
