namespace BestHTTP.Connections.HTTP2
{
	internal enum HTTP2Settings : ushort
	{
		HEADER_TABLE_SIZE = 1,
		ENABLE_PUSH,
		MAX_CONCURRENT_STREAMS,
		INITIAL_WINDOW_SIZE,
		MAX_FRAME_SIZE,
		MAX_HEADER_LIST_SIZE,
		RESERVED,
		ENABLE_CONNECT_PROTOCOL
	}
}
