public enum vx_participant_diagnostic_state_t
{
	participant_diagnostic_state_speaking_while_mic_muted = 1,
	participant_diagnostic_state_speaking_while_mic_volume_zero,
	participant_diagnostic_state_no_capture_device,
	participant_diagnostic_state_no_render_device,
	participant_diagnostic_state_capture_device_read_errors,
	participant_diagnostic_state_render_device_write_errors
}
