public enum vx_sessiongroup_playback_control_type
{
	VX_SESSIONGROUP_PLAYBACK_CONTROL_STOP = 0,
	VX_SESSIONGROUP_PLAYBACK_CONTROL_START = 1,
	VX_SESSIONGROUP_PLAYBACK_CONTROL_PAUSE = 3,
	VX_SESSIONGROUP_PLAYBACK_CONTROL_UNPAUSE = 4
}
