public enum VXA_ERROR_CODES
{
	VXA_SUCCESS,
	VXA_INVALID_PARAMETER,
	VXA_DEVICE_DOES_NOT_EXIST,
	VXA_INTERNAL_ERROR,
	VXA_OUT_OF_MEMORY,
	VXA_INVALID_STATE,
	VXA_NO_MORE_DATA,
	VXA_FEATURE_NOT_SUPPORTED,
	VXA_MAX_DEVICES_EXCEEDED,
	VXA_NO_BUFFERS_AVAILABLE,
	VXA_ACCESS_DENIED
}
